/**
 * Aram API
 * The Aram API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Configuration } from './configuration';
import { AxiosPromise, AxiosInstance } from 'axios';
import { RequestArgs, BaseAPI } from './base';
/**
 *
 * @export
 * @interface AdminLoginDto
 */
export interface AdminLoginDto {
    /**
     *
     * @type {string}
     * @memberof AdminLoginDto
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof AdminLoginDto
     */
    password: string;
}
/**
 *
 * @export
 * @interface CreateGalleryAlbumDto
 */
export interface CreateGalleryAlbumDto {
    /**
     *
     * @type {string}
     * @memberof CreateGalleryAlbumDto
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof CreateGalleryAlbumDto
     */
    coverImageUrl?: string;
    /**
     *
     * @type {number}
     * @memberof CreateGalleryAlbumDto
     */
    imageCount?: number;
    /**
     *
     * @type {string}
     * @memberof CreateGalleryAlbumDto
     */
    visibility?: string;
    /**
     *
     * @type {number}
     * @memberof CreateGalleryAlbumDto
     */
    sortOrder?: number;
}
/**
 *
 * @export
 * @interface CreateGalleryItemDto
 */
export interface CreateGalleryItemDto {
    /**
     *
     * @type {string}
     * @memberof CreateGalleryItemDto
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof CreateGalleryItemDto
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof CreateGalleryItemDto
     */
    altText?: string;
    /**
     *
     * @type {string}
     * @memberof CreateGalleryItemDto
     */
    imagePath: string;
    /**
     *
     * @type {number}
     * @memberof CreateGalleryItemDto
     */
    albumId?: number;
    /**
     *
     * @type {string}
     * @memberof CreateGalleryItemDto
     */
    tagsJson?: string;
    /**
     *
     * @type {number}
     * @memberof CreateGalleryItemDto
     */
    sortOrder?: number;
    /**
     *
     * @type {string}
     * @memberof CreateGalleryItemDto
     */
    caption?: string;
    /**
     *
     * @type {string}
     * @memberof CreateGalleryItemDto
     */
    photographer?: string;
    /**
     *
     * @type {string}
     * @memberof CreateGalleryItemDto
     */
    visibility?: string;
    /**
     *
     * @type {string}
     * @memberof CreateGalleryItemDto
     */
    fileSize?: string;
    /**
     *
     * @type {string}
     * @memberof CreateGalleryItemDto
     */
    thumbnailPath?: string;
    /**
     *
     * @type {string}
     * @memberof CreateGalleryItemDto
     */
    uploadedBy?: string;
    /**
     *
     * @type {boolean}
     * @memberof CreateGalleryItemDto
     */
    altTextGeneratedByAi?: boolean;
}
/**
 *
 * @export
 * @interface CreateGuestDonorDto
 */
export interface CreateGuestDonorDto {
    /**
     *
     * @type {string}
     * @memberof CreateGuestDonorDto
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof CreateGuestDonorDto
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof CreateGuestDonorDto
     */
    mobile: string;
    /**
     *
     * @type {string}
     * @memberof CreateGuestDonorDto
     */
    address: string;
    /**
     * PAN in format AAAAA0000A
     * @type {string}
     * @memberof CreateGuestDonorDto
     */
    pan: string;
    /**
     *
     * @type {string}
     * @memberof CreateGuestDonorDto
     */
    country?: string;
    /**
     *
     * @type {number}
     * @memberof CreateGuestDonorDto
     */
    amount: number;
    /**
     *
     * @type {string}
     * @memberof CreateGuestDonorDto
     */
    donationType: string;
}
/**
 *
 * @export
 * @interface CreateSponsorDto
 */
export interface CreateSponsorDto {
    /**
     *
     * @type {string}
     * @memberof CreateSponsorDto
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof CreateSponsorDto
     */
    logoUrl?: string;
    /**
     *
     * @type {string}
     * @memberof CreateSponsorDto
     */
    websiteUrl?: string;
    /**
     *
     * @type {string}
     * @memberof CreateSponsorDto
     */
    contributionType?: string;
    /**
     *
     * @type {string}
     * @memberof CreateSponsorDto
     */
    tier?: string;
    /**
     *
     * @type {number}
     * @memberof CreateSponsorDto
     */
    displayOrder?: number;
    /**
     *
     * @type {boolean}
     * @memberof CreateSponsorDto
     */
    isActive?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof CreateSponsorDto
     */
    showOnHomepage?: boolean;
    /**
     *
     * @type {string}
     * @memberof CreateSponsorDto
     */
    addedBy?: string;
    /**
     *
     * @type {boolean}
     * @memberof CreateSponsorDto
     */
    featured?: boolean;
    /**
     *
     * @type {string}
     * @memberof CreateSponsorDto
     */
    displayStartDate?: string;
    /**
     *
     * @type {string}
     * @memberof CreateSponsorDto
     */
    displayEndDate?: string;
}
/**
 *
 * @export
 * @interface CreateWebsiteContentDto
 */
export interface CreateWebsiteContentDto {
    /**
     * Section key (e.g. hero, mission_vision)
     * @type {string}
     * @memberof CreateWebsiteContentDto
     */
    sectionKey: string;
    /**
     * JSON content for the section
     * @type {string}
     * @memberof CreateWebsiteContentDto
     */
    contentJson: string;
    /**
     *
     * @type {number}
     * @memberof CreateWebsiteContentDto
     */
    version?: number;
    /**
     *
     * @type {string}
     * @memberof CreateWebsiteContentDto
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof CreateWebsiteContentDto
     */
    slug?: string;
    /**
     *
     * @type {string}
     * @memberof CreateWebsiteContentDto
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof CreateWebsiteContentDto
     */
    modifiedBy?: string;
}
/**
 *
 * @export
 * @interface DonationFormConfigDto
 */
export interface DonationFormConfigDto {
    /**
     * Form publicly accessible when true
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    donationFormEnabled?: boolean;
    /**
     * Shown when form is disabled
     * @type {string}
     * @memberof DonationFormConfigDto
     */
    maintenanceMessage?: string;
    /**
     * Country dropdown vs default India
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    multiCountrySupport?: boolean;
    /**
     * always | threshold | optional_international
     * @type {string}
     * @memberof DonationFormConfigDto
     */
    panRequirement?: string;
    /**
     *
     * @type {number}
     * @memberof DonationFormConfigDto
     */
    panThresholdAmount?: number;
    /**
     *
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    requireAddress?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    requireMobile?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    mobileOtpVerification?: boolean;
    /**
     *
     * @type {Array<number>}
     * @memberof DonationFormConfigDto
     */
    presetAmounts?: Array<number>;
    /**
     *
     * @type {number}
     * @memberof DonationFormConfigDto
     */
    minAmount?: number;
    /**
     *
     * @type {number}
     * @memberof DonationFormConfigDto
     */
    maxAmount?: number;
    /**
     * Show recurring donation option
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    suggestRecurring?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    sendReceiptEmail?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    sendReceiptSms?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    send80GEmail?: boolean;
}
/**
 *
 * @export
 * @interface FeatureConfigItemDto
 */
export interface FeatureConfigItemDto {
    /**
     *
     * @type {string}
     * @memberof FeatureConfigItemDto
     */
    key: string;
    /**
     *
     * @type {string}
     * @memberof FeatureConfigItemDto
     */
    value?: string;
    /**
     *
     * @type {boolean}
     * @memberof FeatureConfigItemDto
     */
    isEnabled: boolean;
}
/**
 *
 * @export
 * @interface ForgotPasswordDto
 */
export interface ForgotPasswordDto {
    /**
     *
     * @type {string}
     * @memberof ForgotPasswordDto
     */
    email: string;
}
/**
 *
 * @export
 * @interface GetFeatureConfigResponseDto
 */
export interface GetFeatureConfigResponseDto {
    /**
     *
     * @type {Array<FeatureConfigItemDto>}
     * @memberof GetFeatureConfigResponseDto
     */
    items: Array<FeatureConfigItemDto>;
    /**
     *
     * @type {DonationFormConfigDto}
     * @memberof GetFeatureConfigResponseDto
     */
    donationForm: DonationFormConfigDto;
}
/**
 *
 * @export
 * @interface LoginDto
 */
export interface LoginDto {
    /**
     *
     * @type {string}
     * @memberof LoginDto
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof LoginDto
     */
    password: string;
}
/**
 *
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     *
     * @type {string}
     * @memberof RegisterDto
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof RegisterDto
     */
    password: string;
    /**
     *
     * @type {string}
     * @memberof RegisterDto
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof RegisterDto
     */
    phone: string;
}
/**
 *
 * @export
 * @interface ResetPasswordDto
 */
export interface ResetPasswordDto {
    /**
     * Reset token from forgot-password email/link
     * @type {string}
     * @memberof ResetPasswordDto
     */
    token: string;
    /**
     *
     * @type {string}
     * @memberof ResetPasswordDto
     */
    newPassword: string;
}
/**
 *
 * @export
 * @interface UpdateGalleryAlbumDto
 */
export interface UpdateGalleryAlbumDto {
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryAlbumDto
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryAlbumDto
     */
    coverImageUrl?: string;
    /**
     *
     * @type {number}
     * @memberof UpdateGalleryAlbumDto
     */
    imageCount?: number;
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryAlbumDto
     */
    visibility?: string;
    /**
     *
     * @type {number}
     * @memberof UpdateGalleryAlbumDto
     */
    sortOrder?: number;
}
/**
 *
 * @export
 * @interface UpdateGalleryItemDto
 */
export interface UpdateGalleryItemDto {
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryItemDto
     */
    title?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryItemDto
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryItemDto
     */
    altText?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryItemDto
     */
    imagePath?: string;
    /**
     *
     * @type {number}
     * @memberof UpdateGalleryItemDto
     */
    albumId?: number;
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryItemDto
     */
    tagsJson?: string;
    /**
     *
     * @type {number}
     * @memberof UpdateGalleryItemDto
     */
    sortOrder?: number;
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryItemDto
     */
    caption?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryItemDto
     */
    photographer?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryItemDto
     */
    visibility?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryItemDto
     */
    fileSize?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryItemDto
     */
    thumbnailPath?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateGalleryItemDto
     */
    uploadedBy?: string;
    /**
     *
     * @type {boolean}
     * @memberof UpdateGalleryItemDto
     */
    altTextGeneratedByAi?: boolean;
}
/**
 *
 * @export
 * @interface UpdateSponsorDto
 */
export interface UpdateSponsorDto {
    /**
     *
     * @type {string}
     * @memberof UpdateSponsorDto
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateSponsorDto
     */
    logoUrl?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateSponsorDto
     */
    websiteUrl?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateSponsorDto
     */
    contributionType?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateSponsorDto
     */
    tier?: string;
    /**
     *
     * @type {number}
     * @memberof UpdateSponsorDto
     */
    displayOrder?: number;
    /**
     *
     * @type {boolean}
     * @memberof UpdateSponsorDto
     */
    isActive?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof UpdateSponsorDto
     */
    showOnHomepage?: boolean;
    /**
     *
     * @type {string}
     * @memberof UpdateSponsorDto
     */
    addedBy?: string;
    /**
     *
     * @type {boolean}
     * @memberof UpdateSponsorDto
     */
    featured?: boolean;
    /**
     *
     * @type {string}
     * @memberof UpdateSponsorDto
     */
    displayStartDate?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateSponsorDto
     */
    displayEndDate?: string;
}
/**
 *
 * @export
 * @interface UpdateWebsiteContentDto
 */
export interface UpdateWebsiteContentDto {
    /**
     *
     * @type {string}
     * @memberof UpdateWebsiteContentDto
     */
    sectionKey?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateWebsiteContentDto
     */
    contentJson?: string;
    /**
     *
     * @type {number}
     * @memberof UpdateWebsiteContentDto
     */
    version?: number;
    /**
     *
     * @type {string}
     * @memberof UpdateWebsiteContentDto
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateWebsiteContentDto
     */
    slug?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateWebsiteContentDto
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateWebsiteContentDto
     */
    modifiedBy?: string;
}
/**
 * AramApi - axios parameter creator
 * @export
 */
export declare const AramApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Get Hello
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    appControllerGetHello: (options?: any) => Promise<RequestArgs>;
};
/**
 * AramApi - functional programming interface
 * @export
 */
export declare const AramApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Get Hello
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    appControllerGetHello(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * AramApi - factory interface
 * @export
 */
export declare const AramApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Get Hello
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    appControllerGetHello(options?: any): AxiosPromise<void>;
};
/**
 * AramApi - object-oriented interface
 * @export
 * @class AramApi
 * @extends {BaseAPI}
 */
export declare class AramApi extends BaseAPI {
    /**
     *
     * @summary Get Hello
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AramApi
     */
    appControllerGetHello(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * AuditApi - axios parameter creator
 * @export
 */
export declare const AuditApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * AuditApi - functional programming interface
 * @export
 */
export declare const AuditApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * AuditApi - factory interface
 * @export
 */
export declare const AuditApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * AuditApi - object-oriented interface
 * @export
 * @class AuditApi
 * @extends {BaseAPI}
 */
export declare class AuditApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    auditControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    auditControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * AuthApi - axios parameter creator
 * @export
 */
export declare const AuthApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Admin portal login
     * @param {AdminLoginDto} adminLoginDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerAdminLogin: (adminLoginDto: AdminLoginDto, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary Admin forgot password
     * @param {ForgotPasswordDto} forgotPasswordDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerForgotPassword: (forgotPasswordDto: ForgotPasswordDto, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary Admin profile (Admin/Super Admin only)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetAdminProfile: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary Get user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetProfile: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary Login user (donor portal)
     * @param {LoginDto} loginDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerLogin: (loginDto: LoginDto, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary Register user (donor portal)
     * @param {RegisterDto} registerDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerRegister: (registerDto: RegisterDto, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary Admin reset password with token
     * @param {ResetPasswordDto} resetPasswordDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerResetPassword: (resetPasswordDto: ResetPasswordDto, options?: any) => Promise<RequestArgs>;
};
/**
 * AuthApi - functional programming interface
 * @export
 */
export declare const AuthApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Admin portal login
     * @param {AdminLoginDto} adminLoginDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerAdminLogin(adminLoginDto: AdminLoginDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Admin forgot password
     * @param {ForgotPasswordDto} forgotPasswordDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerForgotPassword(forgotPasswordDto: ForgotPasswordDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Admin profile (Admin/Super Admin only)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetAdminProfile(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Get user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetProfile(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Login user (donor portal)
     * @param {LoginDto} loginDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerLogin(loginDto: LoginDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Register user (donor portal)
     * @param {RegisterDto} registerDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerRegister(registerDto: RegisterDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Admin reset password with token
     * @param {ResetPasswordDto} resetPasswordDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerResetPassword(resetPasswordDto: ResetPasswordDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * AuthApi - factory interface
 * @export
 */
export declare const AuthApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Admin portal login
     * @param {AdminLoginDto} adminLoginDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerAdminLogin(adminLoginDto: AdminLoginDto, options?: any): AxiosPromise<void>;
    /**
     *
     * @summary Admin forgot password
     * @param {ForgotPasswordDto} forgotPasswordDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerForgotPassword(forgotPasswordDto: ForgotPasswordDto, options?: any): AxiosPromise<void>;
    /**
     *
     * @summary Admin profile (Admin/Super Admin only)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetAdminProfile(options?: any): AxiosPromise<void>;
    /**
     *
     * @summary Get user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetProfile(options?: any): AxiosPromise<void>;
    /**
     *
     * @summary Login user (donor portal)
     * @param {LoginDto} loginDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerLogin(loginDto: LoginDto, options?: any): AxiosPromise<void>;
    /**
     *
     * @summary Register user (donor portal)
     * @param {RegisterDto} registerDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerRegister(registerDto: RegisterDto, options?: any): AxiosPromise<void>;
    /**
     *
     * @summary Admin reset password with token
     * @param {ResetPasswordDto} resetPasswordDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerResetPassword(resetPasswordDto: ResetPasswordDto, options?: any): AxiosPromise<void>;
};
/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export declare class AuthApi extends BaseAPI {
    /**
     *
     * @summary Admin portal login
     * @param {AdminLoginDto} adminLoginDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerAdminLogin(adminLoginDto: AdminLoginDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Admin forgot password
     * @param {ForgotPasswordDto} forgotPasswordDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerForgotPassword(forgotPasswordDto: ForgotPasswordDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Admin profile (Admin/Super Admin only)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerGetAdminProfile(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Get user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerGetProfile(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Login user (donor portal)
     * @param {LoginDto} loginDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerLogin(loginDto: LoginDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Register user (donor portal)
     * @param {RegisterDto} registerDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerRegister(registerDto: RegisterDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Admin reset password with token
     * @param {ResetPasswordDto} resetPasswordDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerResetPassword(resetPasswordDto: ResetPasswordDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * CampaignsApi - axios parameter creator
 * @export
 */
export declare const CampaignsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    campaignsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    campaignsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * CampaignsApi - functional programming interface
 * @export
 */
export declare const CampaignsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    campaignsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    campaignsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * CampaignsApi - factory interface
 * @export
 */
export declare const CampaignsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    campaignsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    campaignsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * CampaignsApi - object-oriented interface
 * @export
 * @class CampaignsApi
 * @extends {BaseAPI}
 */
export declare class CampaignsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignsApi
     */
    campaignsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignsApi
     */
    campaignsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * CommunicationTemplatesApi - axios parameter creator
 * @export
 */
export declare const CommunicationTemplatesApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    communicationTemplatesControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    communicationTemplatesControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * CommunicationTemplatesApi - functional programming interface
 * @export
 */
export declare const CommunicationTemplatesApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    communicationTemplatesControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    communicationTemplatesControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * CommunicationTemplatesApi - factory interface
 * @export
 */
export declare const CommunicationTemplatesApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    communicationTemplatesControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    communicationTemplatesControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * CommunicationTemplatesApi - object-oriented interface
 * @export
 * @class CommunicationTemplatesApi
 * @extends {BaseAPI}
 */
export declare class CommunicationTemplatesApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommunicationTemplatesApi
     */
    communicationTemplatesControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommunicationTemplatesApi
     */
    communicationTemplatesControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * ConfigApi - axios parameter creator
 * @export
 */
export declare const ConfigApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    configControllerGetDonationFormConfig: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    configControllerGetDonationFormConfigFlat: (options?: any) => Promise<RequestArgs>;
};
/**
 * ConfigApi - functional programming interface
 * @export
 */
export declare const ConfigApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    configControllerGetDonationFormConfig(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFeatureConfigResponseDto>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    configControllerGetDonationFormConfigFlat(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * ConfigApi - factory interface
 * @export
 */
export declare const ConfigApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    configControllerGetDonationFormConfig(options?: any): AxiosPromise<GetFeatureConfigResponseDto>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    configControllerGetDonationFormConfigFlat(options?: any): AxiosPromise<void>;
};
/**
 * ConfigApi - object-oriented interface
 * @export
 * @class ConfigApi
 * @extends {BaseAPI}
 */
export declare class ConfigApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConfigApi
     */
    configControllerGetDonationFormConfig(options?: any): Promise<import("axios").AxiosResponse<GetFeatureConfigResponseDto, any, {}>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConfigApi
     */
    configControllerGetDonationFormConfigFlat(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * DonationCategoriesApi - axios parameter creator
 * @export
 */
export declare const DonationCategoriesApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {string} includeDeleted
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donationCategoriesControllerFindAll: (includeDeleted: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donationCategoriesControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * DonationCategoriesApi - functional programming interface
 * @export
 */
export declare const DonationCategoriesApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {string} includeDeleted
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donationCategoriesControllerFindAll(includeDeleted: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donationCategoriesControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * DonationCategoriesApi - factory interface
 * @export
 */
export declare const DonationCategoriesApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {string} includeDeleted
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donationCategoriesControllerFindAll(includeDeleted: string, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donationCategoriesControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * DonationCategoriesApi - object-oriented interface
 * @export
 * @class DonationCategoriesApi
 * @extends {BaseAPI}
 */
export declare class DonationCategoriesApi extends BaseAPI {
    /**
     *
     * @param {string} includeDeleted
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonationCategoriesApi
     */
    donationCategoriesControllerFindAll(includeDeleted: string, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonationCategoriesApi
     */
    donationCategoriesControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * DonorsApi - axios parameter creator
 * @export
 */
export declare const DonorsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerGetMyProfile: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {CreateGuestDonorDto} createGuestDonorDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerGuestDonate: (createGuestDonorDto: CreateGuestDonorDto, options?: any) => Promise<RequestArgs>;
};
/**
 * DonorsApi - functional programming interface
 * @export
 */
export declare const DonorsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerGetMyProfile(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {CreateGuestDonorDto} createGuestDonorDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerGuestDonate(createGuestDonorDto: CreateGuestDonorDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * DonorsApi - factory interface
 * @export
 */
export declare const DonorsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerGetMyProfile(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {CreateGuestDonorDto} createGuestDonorDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerGuestDonate(createGuestDonorDto: CreateGuestDonorDto, options?: any): AxiosPromise<void>;
};
/**
 * DonorsApi - object-oriented interface
 * @export
 * @class DonorsApi
 * @extends {BaseAPI}
 */
export declare class DonorsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonorsApi
     */
    donorsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonorsApi
     */
    donorsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonorsApi
     */
    donorsControllerGetMyProfile(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {CreateGuestDonorDto} createGuestDonorDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonorsApi
     */
    donorsControllerGuestDonate(createGuestDonorDto: CreateGuestDonorDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * EChallansApi - axios parameter creator
 * @export
 */
export declare const EChallansApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    eChallansControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    eChallansControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * EChallansApi - functional programming interface
 * @export
 */
export declare const EChallansApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    eChallansControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    eChallansControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * EChallansApi - factory interface
 * @export
 */
export declare const EChallansApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    eChallansControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    eChallansControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * EChallansApi - object-oriented interface
 * @export
 * @class EChallansApi
 * @extends {BaseAPI}
 */
export declare class EChallansApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EChallansApi
     */
    eChallansControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EChallansApi
     */
    eChallansControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * EnquiriesApi - axios parameter creator
 * @export
 */
export declare const EnquiriesApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enquiriesControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enquiriesControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * EnquiriesApi - functional programming interface
 * @export
 */
export declare const EnquiriesApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enquiriesControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enquiriesControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * EnquiriesApi - factory interface
 * @export
 */
export declare const EnquiriesApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enquiriesControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enquiriesControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * EnquiriesApi - object-oriented interface
 * @export
 * @class EnquiriesApi
 * @extends {BaseAPI}
 */
export declare class EnquiriesApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnquiriesApi
     */
    enquiriesControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnquiriesApi
     */
    enquiriesControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * ExportLogApi - axios parameter creator
 * @export
 */
export declare const ExportLogApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportLogControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportLogControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * ExportLogApi - functional programming interface
 * @export
 */
export declare const ExportLogApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportLogControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportLogControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * ExportLogApi - factory interface
 * @export
 */
export declare const ExportLogApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportLogControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportLogControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * ExportLogApi - object-oriented interface
 * @export
 * @class ExportLogApi
 * @extends {BaseAPI}
 */
export declare class ExportLogApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportLogApi
     */
    exportLogControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportLogApi
     */
    exportLogControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * GalleryApi - axios parameter creator
 * @export
 */
export declare const GalleryApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {CreateGalleryItemDto} createGalleryItemDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerCreate: (createGalleryItemDto: CreateGalleryItemDto, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerRemove: (id: number, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {UpdateGalleryItemDto} updateGalleryItemDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerUpdate: (id: number, updateGalleryItemDto: UpdateGalleryItemDto, options?: any) => Promise<RequestArgs>;
};
/**
 * GalleryApi - functional programming interface
 * @export
 */
export declare const GalleryApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {CreateGalleryItemDto} createGalleryItemDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerCreate(createGalleryItemDto: CreateGalleryItemDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerRemove(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {UpdateGalleryItemDto} updateGalleryItemDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerUpdate(id: number, updateGalleryItemDto: UpdateGalleryItemDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * GalleryApi - factory interface
 * @export
 */
export declare const GalleryApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {CreateGalleryItemDto} createGalleryItemDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerCreate(createGalleryItemDto: CreateGalleryItemDto, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerFindOne(id: number, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerRemove(id: number, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {UpdateGalleryItemDto} updateGalleryItemDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerUpdate(id: number, updateGalleryItemDto: UpdateGalleryItemDto, options?: any): AxiosPromise<void>;
};
/**
 * GalleryApi - object-oriented interface
 * @export
 * @class GalleryApi
 * @extends {BaseAPI}
 */
export declare class GalleryApi extends BaseAPI {
    /**
     *
     * @param {CreateGalleryItemDto} createGalleryItemDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GalleryApi
     */
    galleryControllerCreate(createGalleryItemDto: CreateGalleryItemDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GalleryApi
     */
    galleryControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GalleryApi
     */
    galleryControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GalleryApi
     */
    galleryControllerRemove(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {UpdateGalleryItemDto} updateGalleryItemDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GalleryApi
     */
    galleryControllerUpdate(id: number, updateGalleryItemDto: UpdateGalleryItemDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * GalleryAlbumsApi - axios parameter creator
 * @export
 */
export declare const GalleryAlbumsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {CreateGalleryAlbumDto} createGalleryAlbumDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerCreate: (createGalleryAlbumDto: CreateGalleryAlbumDto, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerRemove: (id: number, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {UpdateGalleryAlbumDto} updateGalleryAlbumDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerUpdate: (id: number, updateGalleryAlbumDto: UpdateGalleryAlbumDto, options?: any) => Promise<RequestArgs>;
};
/**
 * GalleryAlbumsApi - functional programming interface
 * @export
 */
export declare const GalleryAlbumsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {CreateGalleryAlbumDto} createGalleryAlbumDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerCreate(createGalleryAlbumDto: CreateGalleryAlbumDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerRemove(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {UpdateGalleryAlbumDto} updateGalleryAlbumDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerUpdate(id: number, updateGalleryAlbumDto: UpdateGalleryAlbumDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * GalleryAlbumsApi - factory interface
 * @export
 */
export declare const GalleryAlbumsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {CreateGalleryAlbumDto} createGalleryAlbumDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerCreate(createGalleryAlbumDto: CreateGalleryAlbumDto, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerRemove(id: number, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {UpdateGalleryAlbumDto} updateGalleryAlbumDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryAlbumsControllerUpdate(id: number, updateGalleryAlbumDto: UpdateGalleryAlbumDto, options?: any): AxiosPromise<void>;
};
/**
 * GalleryAlbumsApi - object-oriented interface
 * @export
 * @class GalleryAlbumsApi
 * @extends {BaseAPI}
 */
export declare class GalleryAlbumsApi extends BaseAPI {
    /**
     *
     * @param {CreateGalleryAlbumDto} createGalleryAlbumDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GalleryAlbumsApi
     */
    galleryAlbumsControllerCreate(createGalleryAlbumDto: CreateGalleryAlbumDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GalleryAlbumsApi
     */
    galleryAlbumsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GalleryAlbumsApi
     */
    galleryAlbumsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GalleryAlbumsApi
     */
    galleryAlbumsControllerRemove(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {UpdateGalleryAlbumDto} updateGalleryAlbumDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GalleryAlbumsApi
     */
    galleryAlbumsControllerUpdate(id: number, updateGalleryAlbumDto: UpdateGalleryAlbumDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * NotificationsApi - axios parameter creator
 * @export
 */
export declare const NotificationsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * NotificationsApi - functional programming interface
 * @export
 */
export declare const NotificationsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * NotificationsApi - factory interface
 * @export
 */
export declare const NotificationsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * NotificationsApi - object-oriented interface
 * @export
 * @class NotificationsApi
 * @extends {BaseAPI}
 */
export declare class NotificationsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    notificationsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    notificationsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * PaymentGatewayApi - axios parameter creator
 * @export
 */
export declare const PaymentGatewayApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentGatewayControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentGatewayControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * PaymentGatewayApi - functional programming interface
 * @export
 */
export declare const PaymentGatewayApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentGatewayControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentGatewayControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * PaymentGatewayApi - factory interface
 * @export
 */
export declare const PaymentGatewayApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentGatewayControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentGatewayControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * PaymentGatewayApi - object-oriented interface
 * @export
 * @class PaymentGatewayApi
 * @extends {BaseAPI}
 */
export declare class PaymentGatewayApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentGatewayApi
     */
    paymentGatewayControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentGatewayApi
     */
    paymentGatewayControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * ReceiptsApi - axios parameter creator
 * @export
 */
export declare const ReceiptsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    receiptsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    receiptsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * ReceiptsApi - functional programming interface
 * @export
 */
export declare const ReceiptsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    receiptsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    receiptsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * ReceiptsApi - factory interface
 * @export
 */
export declare const ReceiptsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    receiptsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    receiptsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * ReceiptsApi - object-oriented interface
 * @export
 * @class ReceiptsApi
 * @extends {BaseAPI}
 */
export declare class ReceiptsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiptsApi
     */
    receiptsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiptsApi
     */
    receiptsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * ReconciliationApi - axios parameter creator
 * @export
 */
export declare const ReconciliationApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconciliationControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconciliationControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * ReconciliationApi - functional programming interface
 * @export
 */
export declare const ReconciliationApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconciliationControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconciliationControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * ReconciliationApi - factory interface
 * @export
 */
export declare const ReconciliationApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconciliationControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconciliationControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * ReconciliationApi - object-oriented interface
 * @export
 * @class ReconciliationApi
 * @extends {BaseAPI}
 */
export declare class ReconciliationApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReconciliationApi
     */
    reconciliationControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReconciliationApi
     */
    reconciliationControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * RefundsApi - axios parameter creator
 * @export
 */
export declare const RefundsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refundsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refundsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * RefundsApi - functional programming interface
 * @export
 */
export declare const RefundsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refundsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refundsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * RefundsApi - factory interface
 * @export
 */
export declare const RefundsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refundsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refundsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * RefundsApi - object-oriented interface
 * @export
 * @class RefundsApi
 * @extends {BaseAPI}
 */
export declare class RefundsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RefundsApi
     */
    refundsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RefundsApi
     */
    refundsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * SponsorsApi - axios parameter creator
 * @export
 */
export declare const SponsorsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {CreateSponsorDto} createSponsorDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerCreate: (createSponsorDto: CreateSponsorDto, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerRemove: (id: number, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {UpdateSponsorDto} updateSponsorDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerUpdate: (id: number, updateSponsorDto: UpdateSponsorDto, options?: any) => Promise<RequestArgs>;
};
/**
 * SponsorsApi - functional programming interface
 * @export
 */
export declare const SponsorsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {CreateSponsorDto} createSponsorDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerCreate(createSponsorDto: CreateSponsorDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerRemove(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {UpdateSponsorDto} updateSponsorDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerUpdate(id: number, updateSponsorDto: UpdateSponsorDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * SponsorsApi - factory interface
 * @export
 */
export declare const SponsorsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {CreateSponsorDto} createSponsorDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerCreate(createSponsorDto: CreateSponsorDto, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerRemove(id: number, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {UpdateSponsorDto} updateSponsorDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerUpdate(id: number, updateSponsorDto: UpdateSponsorDto, options?: any): AxiosPromise<void>;
};
/**
 * SponsorsApi - object-oriented interface
 * @export
 * @class SponsorsApi
 * @extends {BaseAPI}
 */
export declare class SponsorsApi extends BaseAPI {
    /**
     *
     * @param {CreateSponsorDto} createSponsorDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SponsorsApi
     */
    sponsorsControllerCreate(createSponsorDto: CreateSponsorDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SponsorsApi
     */
    sponsorsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SponsorsApi
     */
    sponsorsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SponsorsApi
     */
    sponsorsControllerRemove(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {UpdateSponsorDto} updateSponsorDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SponsorsApi
     */
    sponsorsControllerUpdate(id: number, updateSponsorDto: UpdateSponsorDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * TransactionsApi - axios parameter creator
 * @export
 */
export declare const TransactionsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    transactionsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    transactionsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * TransactionsApi - functional programming interface
 * @export
 */
export declare const TransactionsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    transactionsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    transactionsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * TransactionsApi - factory interface
 * @export
 */
export declare const TransactionsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    transactionsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    transactionsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * TransactionsApi - object-oriented interface
 * @export
 * @class TransactionsApi
 * @extends {BaseAPI}
 */
export declare class TransactionsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    transactionsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    transactionsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * WebsiteContentApi - axios parameter creator
 * @export
 */
export declare const WebsiteContentApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {CreateWebsiteContentDto} createWebsiteContentDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerCreate: (createWebsiteContentDto: CreateWebsiteContentDto, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {string} sectionKey
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerFindAll: (sectionKey: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerRemove: (id: number, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {UpdateWebsiteContentDto} updateWebsiteContentDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerUpdate: (id: number, updateWebsiteContentDto: UpdateWebsiteContentDto, options?: any) => Promise<RequestArgs>;
};
/**
 * WebsiteContentApi - functional programming interface
 * @export
 */
export declare const WebsiteContentApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {CreateWebsiteContentDto} createWebsiteContentDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerCreate(createWebsiteContentDto: CreateWebsiteContentDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {string} sectionKey
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerFindAll(sectionKey: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerRemove(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {UpdateWebsiteContentDto} updateWebsiteContentDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerUpdate(id: number, updateWebsiteContentDto: UpdateWebsiteContentDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * WebsiteContentApi - factory interface
 * @export
 */
export declare const WebsiteContentApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {CreateWebsiteContentDto} createWebsiteContentDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerCreate(createWebsiteContentDto: CreateWebsiteContentDto, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {string} sectionKey
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerFindAll(sectionKey: string, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerFindOne(id: number, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerRemove(id: number, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {UpdateWebsiteContentDto} updateWebsiteContentDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerUpdate(id: number, updateWebsiteContentDto: UpdateWebsiteContentDto, options?: any): AxiosPromise<void>;
};
/**
 * WebsiteContentApi - object-oriented interface
 * @export
 * @class WebsiteContentApi
 * @extends {BaseAPI}
 */
export declare class WebsiteContentApi extends BaseAPI {
    /**
     *
     * @param {CreateWebsiteContentDto} createWebsiteContentDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebsiteContentApi
     */
    websiteContentControllerCreate(createWebsiteContentDto: CreateWebsiteContentDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {string} sectionKey
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebsiteContentApi
     */
    websiteContentControllerFindAll(sectionKey: string, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebsiteContentApi
     */
    websiteContentControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebsiteContentApi
     */
    websiteContentControllerRemove(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {UpdateWebsiteContentDto} updateWebsiteContentDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebsiteContentApi
     */
    websiteContentControllerUpdate(id: number, updateWebsiteContentDto: UpdateWebsiteContentDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
//# sourceMappingURL=api.d.ts.map