/**
 * Aram API
 * The Aram API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Configuration } from './configuration';
import { AxiosPromise, AxiosInstance } from 'axios';
import { RequestArgs, BaseAPI } from './base';
/**
 *
 * @export
 * @interface DonationFormConfigDto
 */
export interface DonationFormConfigDto {
    /**
     * Form publicly accessible when true
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    donationFormEnabled?: boolean;
    /**
     * Shown when form is disabled
     * @type {string}
     * @memberof DonationFormConfigDto
     */
    maintenanceMessage?: string;
    /**
     * Test mode – no real transactions
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    testMode?: boolean;
    /**
     * Country dropdown vs default India
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    multiCountrySupport?: boolean;
    /**
     * always | threshold | optional_international
     * @type {string}
     * @memberof DonationFormConfigDto
     */
    panRequirement?: string;
    /**
     *
     * @type {number}
     * @memberof DonationFormConfigDto
     */
    panThresholdAmount?: number;
    /**
     *
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    requireAddress?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    requireMobile?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    mobileOtpVerification?: boolean;
    /**
     *
     * @type {Array<number>}
     * @memberof DonationFormConfigDto
     */
    presetAmounts?: Array<number>;
    /**
     *
     * @type {number}
     * @memberof DonationFormConfigDto
     */
    minAmount?: number;
    /**
     *
     * @type {number}
     * @memberof DonationFormConfigDto
     */
    maxAmount?: number;
    /**
     * Show recurring donation option
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    suggestRecurring?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    sendReceiptEmail?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    sendReceiptSms?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DonationFormConfigDto
     */
    send80GEmail?: boolean;
}
/**
 *
 * @export
 * @interface FeatureConfigItemDto
 */
export interface FeatureConfigItemDto {
    /**
     *
     * @type {string}
     * @memberof FeatureConfigItemDto
     */
    key: string;
    /**
     *
     * @type {string}
     * @memberof FeatureConfigItemDto
     */
    value?: string;
    /**
     *
     * @type {boolean}
     * @memberof FeatureConfigItemDto
     */
    isEnabled: boolean;
}
/**
 *
 * @export
 * @interface GetFeatureConfigResponseDto
 */
export interface GetFeatureConfigResponseDto {
    /**
     *
     * @type {Array<FeatureConfigItemDto>}
     * @memberof GetFeatureConfigResponseDto
     */
    items: Array<FeatureConfigItemDto>;
    /**
     *
     * @type {DonationFormConfigDto}
     * @memberof GetFeatureConfigResponseDto
     */
    donationForm: DonationFormConfigDto;
}
/**
 *
 * @export
 * @interface LoginDto
 */
export interface LoginDto {
    /**
     *
     * @type {string}
     * @memberof LoginDto
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof LoginDto
     */
    password: string;
}
/**
 *
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     *
     * @type {string}
     * @memberof RegisterDto
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof RegisterDto
     */
    password: string;
    /**
     *
     * @type {string}
     * @memberof RegisterDto
     */
    name: string;
}
/**
 * AramApi - axios parameter creator
 * @export
 */
export declare const AramApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Get Hello
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    appControllerGetHello: (options?: any) => Promise<RequestArgs>;
};
/**
 * AramApi - functional programming interface
 * @export
 */
export declare const AramApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Get Hello
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    appControllerGetHello(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * AramApi - factory interface
 * @export
 */
export declare const AramApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Get Hello
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    appControllerGetHello(options?: any): AxiosPromise<void>;
};
/**
 * AramApi - object-oriented interface
 * @export
 * @class AramApi
 * @extends {BaseAPI}
 */
export declare class AramApi extends BaseAPI {
    /**
     *
     * @summary Get Hello
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AramApi
     */
    appControllerGetHello(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * AuditApi - axios parameter creator
 * @export
 */
export declare const AuditApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * AuditApi - functional programming interface
 * @export
 */
export declare const AuditApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * AuditApi - factory interface
 * @export
 */
export declare const AuditApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * AuditApi - object-oriented interface
 * @export
 * @class AuditApi
 * @extends {BaseAPI}
 */
export declare class AuditApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    auditControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    auditControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * AuthApi - axios parameter creator
 * @export
 */
export declare const AuthApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Get user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetProfile: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary Login user
     * @param {LoginDto} loginDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerLogin: (loginDto: LoginDto, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary Register user
     * @param {RegisterDto} registerDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerRegister: (registerDto: RegisterDto, options?: any) => Promise<RequestArgs>;
};
/**
 * AuthApi - functional programming interface
 * @export
 */
export declare const AuthApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Get user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetProfile(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Login user
     * @param {LoginDto} loginDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerLogin(loginDto: LoginDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Register user
     * @param {RegisterDto} registerDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerRegister(registerDto: RegisterDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * AuthApi - factory interface
 * @export
 */
export declare const AuthApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Get user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetProfile(options?: any): AxiosPromise<void>;
    /**
     *
     * @summary Login user
     * @param {LoginDto} loginDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerLogin(loginDto: LoginDto, options?: any): AxiosPromise<void>;
    /**
     *
     * @summary Register user
     * @param {RegisterDto} registerDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerRegister(registerDto: RegisterDto, options?: any): AxiosPromise<void>;
};
/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export declare class AuthApi extends BaseAPI {
    /**
     *
     * @summary Get user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerGetProfile(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Login user
     * @param {LoginDto} loginDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerLogin(loginDto: LoginDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Register user
     * @param {RegisterDto} registerDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerRegister(registerDto: RegisterDto, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * CampaignsApi - axios parameter creator
 * @export
 */
export declare const CampaignsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    campaignsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    campaignsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * CampaignsApi - functional programming interface
 * @export
 */
export declare const CampaignsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    campaignsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    campaignsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * CampaignsApi - factory interface
 * @export
 */
export declare const CampaignsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    campaignsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    campaignsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * CampaignsApi - object-oriented interface
 * @export
 * @class CampaignsApi
 * @extends {BaseAPI}
 */
export declare class CampaignsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignsApi
     */
    campaignsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignsApi
     */
    campaignsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * CommunicationTemplatesApi - axios parameter creator
 * @export
 */
export declare const CommunicationTemplatesApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    communicationTemplatesControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    communicationTemplatesControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * CommunicationTemplatesApi - functional programming interface
 * @export
 */
export declare const CommunicationTemplatesApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    communicationTemplatesControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    communicationTemplatesControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * CommunicationTemplatesApi - factory interface
 * @export
 */
export declare const CommunicationTemplatesApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    communicationTemplatesControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    communicationTemplatesControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * CommunicationTemplatesApi - object-oriented interface
 * @export
 * @class CommunicationTemplatesApi
 * @extends {BaseAPI}
 */
export declare class CommunicationTemplatesApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommunicationTemplatesApi
     */
    communicationTemplatesControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommunicationTemplatesApi
     */
    communicationTemplatesControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * ConfigApi - axios parameter creator
 * @export
 */
export declare const ConfigApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    configControllerGetDonationFormConfig: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    configControllerGetDonationFormConfigFlat: (options?: any) => Promise<RequestArgs>;
};
/**
 * ConfigApi - functional programming interface
 * @export
 */
export declare const ConfigApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    configControllerGetDonationFormConfig(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFeatureConfigResponseDto>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    configControllerGetDonationFormConfigFlat(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * ConfigApi - factory interface
 * @export
 */
export declare const ConfigApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    configControllerGetDonationFormConfig(options?: any): AxiosPromise<GetFeatureConfigResponseDto>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    configControllerGetDonationFormConfigFlat(options?: any): AxiosPromise<void>;
};
/**
 * ConfigApi - object-oriented interface
 * @export
 * @class ConfigApi
 * @extends {BaseAPI}
 */
export declare class ConfigApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConfigApi
     */
    configControllerGetDonationFormConfig(options?: any): Promise<import("axios").AxiosResponse<GetFeatureConfigResponseDto, any, {}>>;
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConfigApi
     */
    configControllerGetDonationFormConfigFlat(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * DonationCategoriesApi - axios parameter creator
 * @export
 */
export declare const DonationCategoriesApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {string} includeDeleted
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donationCategoriesControllerFindAll: (includeDeleted: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donationCategoriesControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * DonationCategoriesApi - functional programming interface
 * @export
 */
export declare const DonationCategoriesApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {string} includeDeleted
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donationCategoriesControllerFindAll(includeDeleted: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donationCategoriesControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * DonationCategoriesApi - factory interface
 * @export
 */
export declare const DonationCategoriesApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {string} includeDeleted
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donationCategoriesControllerFindAll(includeDeleted: string, options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donationCategoriesControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * DonationCategoriesApi - object-oriented interface
 * @export
 * @class DonationCategoriesApi
 * @extends {BaseAPI}
 */
export declare class DonationCategoriesApi extends BaseAPI {
    /**
     *
     * @param {string} includeDeleted
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonationCategoriesApi
     */
    donationCategoriesControllerFindAll(includeDeleted: string, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonationCategoriesApi
     */
    donationCategoriesControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * DonorsApi - axios parameter creator
 * @export
 */
export declare const DonorsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * DonorsApi - functional programming interface
 * @export
 */
export declare const DonorsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * DonorsApi - factory interface
 * @export
 */
export declare const DonorsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    donorsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * DonorsApi - object-oriented interface
 * @export
 * @class DonorsApi
 * @extends {BaseAPI}
 */
export declare class DonorsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonorsApi
     */
    donorsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonorsApi
     */
    donorsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * EChallansApi - axios parameter creator
 * @export
 */
export declare const EChallansApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    eChallansControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    eChallansControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * EChallansApi - functional programming interface
 * @export
 */
export declare const EChallansApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    eChallansControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    eChallansControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * EChallansApi - factory interface
 * @export
 */
export declare const EChallansApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    eChallansControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    eChallansControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * EChallansApi - object-oriented interface
 * @export
 * @class EChallansApi
 * @extends {BaseAPI}
 */
export declare class EChallansApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EChallansApi
     */
    eChallansControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EChallansApi
     */
    eChallansControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * EnquiriesApi - axios parameter creator
 * @export
 */
export declare const EnquiriesApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enquiriesControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enquiriesControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * EnquiriesApi - functional programming interface
 * @export
 */
export declare const EnquiriesApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enquiriesControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enquiriesControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * EnquiriesApi - factory interface
 * @export
 */
export declare const EnquiriesApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enquiriesControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enquiriesControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * EnquiriesApi - object-oriented interface
 * @export
 * @class EnquiriesApi
 * @extends {BaseAPI}
 */
export declare class EnquiriesApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnquiriesApi
     */
    enquiriesControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnquiriesApi
     */
    enquiriesControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * ExportLogApi - axios parameter creator
 * @export
 */
export declare const ExportLogApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportLogControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportLogControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * ExportLogApi - functional programming interface
 * @export
 */
export declare const ExportLogApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportLogControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportLogControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * ExportLogApi - factory interface
 * @export
 */
export declare const ExportLogApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportLogControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportLogControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * ExportLogApi - object-oriented interface
 * @export
 * @class ExportLogApi
 * @extends {BaseAPI}
 */
export declare class ExportLogApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportLogApi
     */
    exportLogControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportLogApi
     */
    exportLogControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * GalleryApi - axios parameter creator
 * @export
 */
export declare const GalleryApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * GalleryApi - functional programming interface
 * @export
 */
export declare const GalleryApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * GalleryApi - factory interface
 * @export
 */
export declare const GalleryApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    galleryControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * GalleryApi - object-oriented interface
 * @export
 * @class GalleryApi
 * @extends {BaseAPI}
 */
export declare class GalleryApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GalleryApi
     */
    galleryControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GalleryApi
     */
    galleryControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * NotificationsApi - axios parameter creator
 * @export
 */
export declare const NotificationsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * NotificationsApi - functional programming interface
 * @export
 */
export declare const NotificationsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * NotificationsApi - factory interface
 * @export
 */
export declare const NotificationsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    notificationsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * NotificationsApi - object-oriented interface
 * @export
 * @class NotificationsApi
 * @extends {BaseAPI}
 */
export declare class NotificationsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    notificationsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    notificationsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * PaymentGatewayApi - axios parameter creator
 * @export
 */
export declare const PaymentGatewayApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentGatewayControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentGatewayControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * PaymentGatewayApi - functional programming interface
 * @export
 */
export declare const PaymentGatewayApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentGatewayControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentGatewayControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * PaymentGatewayApi - factory interface
 * @export
 */
export declare const PaymentGatewayApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentGatewayControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentGatewayControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * PaymentGatewayApi - object-oriented interface
 * @export
 * @class PaymentGatewayApi
 * @extends {BaseAPI}
 */
export declare class PaymentGatewayApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentGatewayApi
     */
    paymentGatewayControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentGatewayApi
     */
    paymentGatewayControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * ReceiptsApi - axios parameter creator
 * @export
 */
export declare const ReceiptsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    receiptsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    receiptsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * ReceiptsApi - functional programming interface
 * @export
 */
export declare const ReceiptsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    receiptsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    receiptsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * ReceiptsApi - factory interface
 * @export
 */
export declare const ReceiptsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    receiptsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    receiptsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * ReceiptsApi - object-oriented interface
 * @export
 * @class ReceiptsApi
 * @extends {BaseAPI}
 */
export declare class ReceiptsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiptsApi
     */
    receiptsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiptsApi
     */
    receiptsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * ReconciliationApi - axios parameter creator
 * @export
 */
export declare const ReconciliationApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconciliationControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconciliationControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * ReconciliationApi - functional programming interface
 * @export
 */
export declare const ReconciliationApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconciliationControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconciliationControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * ReconciliationApi - factory interface
 * @export
 */
export declare const ReconciliationApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconciliationControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reconciliationControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * ReconciliationApi - object-oriented interface
 * @export
 * @class ReconciliationApi
 * @extends {BaseAPI}
 */
export declare class ReconciliationApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReconciliationApi
     */
    reconciliationControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReconciliationApi
     */
    reconciliationControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * RefundsApi - axios parameter creator
 * @export
 */
export declare const RefundsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refundsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refundsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * RefundsApi - functional programming interface
 * @export
 */
export declare const RefundsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refundsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refundsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * RefundsApi - factory interface
 * @export
 */
export declare const RefundsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refundsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refundsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * RefundsApi - object-oriented interface
 * @export
 * @class RefundsApi
 * @extends {BaseAPI}
 */
export declare class RefundsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RefundsApi
     */
    refundsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RefundsApi
     */
    refundsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * SponsorsApi - axios parameter creator
 * @export
 */
export declare const SponsorsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * SponsorsApi - functional programming interface
 * @export
 */
export declare const SponsorsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * SponsorsApi - factory interface
 * @export
 */
export declare const SponsorsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sponsorsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * SponsorsApi - object-oriented interface
 * @export
 * @class SponsorsApi
 * @extends {BaseAPI}
 */
export declare class SponsorsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SponsorsApi
     */
    sponsorsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SponsorsApi
     */
    sponsorsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * TransactionsApi - axios parameter creator
 * @export
 */
export declare const TransactionsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    transactionsControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    transactionsControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * TransactionsApi - functional programming interface
 * @export
 */
export declare const TransactionsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    transactionsControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    transactionsControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * TransactionsApi - factory interface
 * @export
 */
export declare const TransactionsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    transactionsControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    transactionsControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * TransactionsApi - object-oriented interface
 * @export
 * @class TransactionsApi
 * @extends {BaseAPI}
 */
export declare class TransactionsApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    transactionsControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    transactionsControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
/**
 * WebsiteContentApi - axios parameter creator
 * @export
 */
export declare const WebsiteContentApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerFindAll: (options?: any) => Promise<RequestArgs>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerFindOne: (id: number, options?: any) => Promise<RequestArgs>;
};
/**
 * WebsiteContentApi - functional programming interface
 * @export
 */
export declare const WebsiteContentApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerFindAll(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerFindOne(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * WebsiteContentApi - factory interface
 * @export
 */
export declare const WebsiteContentApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerFindAll(options?: any): AxiosPromise<void>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    websiteContentControllerFindOne(id: number, options?: any): AxiosPromise<void>;
};
/**
 * WebsiteContentApi - object-oriented interface
 * @export
 * @class WebsiteContentApi
 * @extends {BaseAPI}
 */
export declare class WebsiteContentApi extends BaseAPI {
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebsiteContentApi
     */
    websiteContentControllerFindAll(options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebsiteContentApi
     */
    websiteContentControllerFindOne(id: number, options?: any): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
//# sourceMappingURL=api.d.ts.map