import { useState } from 'react';
import {
  FileText,
  Download,
  Settings,
  Search,
  Calendar,
  Filter,
  AlertTriangle,
  Mail,
  MessageSquare,
  Eye,
  Send,
  RotateCcw,
  History,
  X,
  ChevronDown,
  ChevronRight,
} from 'lucide-react';

interface Receipt {
  id: string;
  receiptNo: string;
  receiptDate: string;
  donorName: string;
  pan: string;
  amount: number;
  category: string;
  is80G: boolean;
  donationType: string;
  paymentMethod: string;
  status: string;
  email: string;
  mobile: string;
  generatedOn: string;
  generatedBy: string;
  templateVersion: string;
  deliveryStatus: {
    email: 'sent' | 'failed' | 'pending';
    sms: 'sent' | 'failed' | 'pending';
  };
  paymentId: string;
  orderId: string;
  refundStatus: 'none' | 'partial' | 'full';
}

// Mock data
const mockReceipts: Receipt[] = [
  {
    id: '1',
    receiptNo: 'ARAM/2025-26/00123',
    receiptDate: '2026-01-15',
    donorName: 'Rajesh Kumar',
    pan: 'ABCDE1234F',
    amount: 50000,
    category: 'General Donation',
    is80G: true,
    donationType: 'Online',
    paymentMethod: 'UPI',
    status: 'Generated',
    email: 'rajesh.k@email.com',
    mobile: '+91 98765 43210',
    generatedOn: '2026-01-15 10:30 AM',
    generatedBy: 'System',
    templateVersion: 'v2.1',
    deliveryStatus: { email: 'sent', sms: 'sent' },
    paymentId: 'pay_123456789',
    orderId: 'order_987654321',
    refundStatus: 'none',
  },
  {
    id: '2',
    receiptNo: 'ARAM/2025-26/00124',
    receiptDate: '2026-01-16',
    donorName: 'Priya Sharma',
    pan: 'FGHIJ5678K',
    amount: 25000,
    category: 'Education Fund',
    is80G: true,
    donationType: 'E-Challan',
    paymentMethod: 'Bank Transfer',
    status: 'Generated',
    email: 'priya.s@email.com',
    mobile: '+91 87654 32109',
    generatedOn: '2026-01-16 02:15 PM',
    generatedBy: 'Admin User',
    templateVersion: 'v2.1',
    deliveryStatus: { email: 'sent', sms: 'failed' },
    paymentId: 'offline_001',
    orderId: 'ECH-2026-001',
    refundStatus: 'none',
  },
  // Missing: ARAM/2025-26/00125, 00126
  {
    id: '3',
    receiptNo: 'ARAM/2025-26/00127',
    receiptDate: '2026-01-18',
    donorName: 'Amit Patel',
    pan: 'KLMNO9012P',
    amount: 100000,
    category: 'Health & Medical',
    is80G: false,
    donationType: 'Online',
    paymentMethod: 'Card',
    status: 'Generated',
    email: 'amit.p@email.com',
    mobile: '+91 76543 21098',
    generatedOn: '2026-01-18 09:45 AM',
    generatedBy: 'System',
    templateVersion: 'v2.1',
    deliveryStatus: { email: 'sent', sms: 'sent' },
    paymentId: 'pay_234567890',
    orderId: 'order_876543210',
    refundStatus: 'none',
  },
  {
    id: '4',
    receiptNo: 'ARAM/2025-26/00128',
    receiptDate: '2026-01-19',
    donorName: 'Sneha Reddy',
    pan: 'PQRST3456U',
    amount: 15000,
    category: 'General Donation',
    is80G: true,
    donationType: 'Online',
    paymentMethod: 'Wallet',
    status: 'Pending Generation',
    email: 'sneha.r@email.com',
    mobile: '+91 65432 10987',
    generatedOn: '-',
    generatedBy: '-',
    templateVersion: '-',
    deliveryStatus: { email: 'pending', sms: 'pending' },
    paymentId: 'pay_345678901',
    orderId: 'order_765432109',
    refundStatus: 'none',
  },
  {
    id: '5',
    receiptNo: 'ARAM/2025-26/00129',
    receiptDate: '2026-01-20',
    donorName: 'Vikram Singh',
    pan: 'UVWXY7890Z',
    amount: 75000,
    category: 'Infrastructure',
    is80G: true,
    donationType: 'E-Challan',
    paymentMethod: 'Cheque',
    status: 'Generated',
    email: 'vikram.s@email.com',
    mobile: '+91 54321 09876',
    generatedOn: '2026-01-20 11:20 AM',
    generatedBy: 'Finance Manager',
    templateVersion: 'v2.1',
    deliveryStatus: { email: 'failed', sms: 'sent' },
    paymentId: 'offline_002',
    orderId: 'ECH-2026-002',
    refundStatus: 'none',
  },
];

const COLUMN_OPTIONS = [
  { id: 'receiptNo', label: 'Receipt No', core: true },
  { id: 'receiptDate', label: 'Receipt Date', core: true },
  { id: 'donorName', label: 'Donor Name', core: true },
  { id: 'pan', label: 'PAN', core: true },
  { id: 'amount', label: 'Amount', core: true },
  { id: 'category', label: 'Category', core: true },
  { id: 'is80G', label: '80G Eligible', core: true },
  { id: 'donationType', label: 'Donation Type', core: false },
  { id: 'paymentMethod', label: 'Payment Method', core: false },
  { id: 'status', label: 'Status', core: false },
  { id: 'email', label: 'Donor Email', core: false },
  { id: 'mobile', label: 'Donor Mobile', core: false },
  { id: 'generatedOn', label: 'Generated On', core: false },
  { id: 'generatedBy', label: 'Generated By', core: false },
  { id: 'templateVersion', label: 'Template Version', core: false },
  { id: 'deliveryStatus', label: 'Delivery Status', core: false },
  { id: 'paymentId', label: 'Payment ID', core: false },
  { id: 'orderId', label: 'Order ID', core: false },
  { id: 'refundStatus', label: 'Refund Status', core: false },
];

export function ReceiptRegisterScreen() {
  const [showFilters, setShowFilters] = useState(true);
  const [showColumnConfig, setShowColumnConfig] = useState(false);
  const [showGapDetails, setShowGapDetails] = useState(false);
  const [selectedReceipt, setSelectedReceipt] = useState<Receipt | null>(null);
  const [showAuditTrail, setShowAuditTrail] = useState(false);
  const [showReasonModal, setShowReasonModal] = useState(false);
  const [reasonAction, setReasonAction] = useState<string>('');
  const [showExportOptions, setShowExportOptions] = useState(false);
  
  // Visible columns state
  const [visibleColumns, setVisibleColumns] = useState<string[]>(
    COLUMN_OPTIONS.filter(col => col.core).map(col => col.id)
  );
  
  // Filter states
  const [filters, setFilters] = useState({
    dateRange: 'This Month',
    receiptTypes: ['Online Donation', 'E-Challan'],
    statuses: ['Generated'],
    is80G: 'all',
    amountMin: '',
    amountMax: '',
    searchTerm: '',
    showRefunded: 'exclude',
  });
  
  const [gapDetection, setGapDetection] = useState(true);
  
  // Calculate summary metrics
  const totalReceipts = mockReceipts.length;
  const totalAmount = mockReceipts.reduce((sum, r) => sum + r.amount, 0);
  const total80GReceipts = mockReceipts.filter(r => r.is80G).length;
  const total80GAmount = mockReceipts.filter(r => r.is80G).reduce((sum, r) => sum + r.amount, 0);
  const deliveryFailures = mockReceipts.filter(
    r => r.deliveryStatus.email === 'failed' || r.deliveryStatus.sms === 'failed'
  ).length;
  const missingReceipts = ['ARAM/2025-26/00125', 'ARAM/2025-26/00126'];
  
  const handleColumnToggle = (columnId: string) => {
    setVisibleColumns(prev =>
      prev.includes(columnId)
        ? prev.filter(id => id !== columnId)
        : [...prev, columnId]
    );
  };
  
  const handleExport = (format: 'excel' | 'csv' | 'pdf') => {
    console.log(`Exporting as ${format}`);
    setShowExportOptions(false);
    // This would trigger actual export with watermarking and logging
  };
  
  const handleResend = (type: 'email' | 'sms', receipt: Receipt) => {
    setSelectedReceipt(receipt);
    setReasonAction(`Resend ${type.toUpperCase()}`);
    setShowReasonModal(true);
  };
  
  const handleRegenerate = (receipt: Receipt) => {
    setSelectedReceipt(receipt);
    setReasonAction('Regenerate PDF');
    setShowReasonModal(true);
  };
  
  const handleViewAudit = (receipt: Receipt) => {
    setSelectedReceipt(receipt);
    setShowAuditTrail(true);
  };
  
  return (
    <div className="flex flex-col bg-[#F8F8F8]">
      {/* Header */}
      <div className="bg-white rounded-[16px] border border-[#DBDBDB] p-[24px] mb-[24px]">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-[20px] leading-[28px] font-semibold text-[#0D0D0D]">
              Receipt Register
            </h1>
            <p className="text-[13px] leading-[18px] text-[#6E6E6E] mt-1">
              Complete register with compliance tracking and gap detection
            </p>
          </div>
          
          <div className="flex items-center gap-3">
            <button
              onClick={() => setShowColumnConfig(!showColumnConfig)}
              className="h-[44px] px-[20px] rounded-full border border-[#DBDBDB] bg-white hover:bg-[#F3F3F3] transition-colors flex items-center gap-2 text-[14px] font-medium text-[#3D3D3D]"
            >
              <Settings className="w-4 h-4" />
              Configure Columns
            </button>
            
            <button
              onClick={() => setShowFilters(!showFilters)}
              className="h-[44px] px-[20px] rounded-full border border-[#DBDBDB] bg-white hover:bg-[#F3F3F3] transition-colors flex items-center gap-2 text-[14px] font-medium text-[#3D3D3D]"
            >
              <Filter className="w-4 h-4" />
              {showFilters ? 'Hide Filters' : 'Show Filters'}
            </button>
            
            <div className="relative">
              <button
                onClick={() => setShowExportOptions(!showExportOptions)}
                className="h-[44px] px-[20px] rounded-full bg-[#F36A4F] hover:bg-[#E55A3F] transition-colors flex items-center gap-2 text-[14px] font-medium text-white"
              >
                <Download className="w-4 h-4" />
                Export Register
              </button>
              
              {showExportOptions && (
                <div className="absolute right-0 top-full mt-2 w-[240px] bg-white rounded-[16px] border border-[#DBDBDB] shadow-lg p-2 z-50">
                  <div className="p-3 border-b border-[#DBDBDB]">
                    <p className="text-[13px] font-medium text-[#0D0D0D]">Export Options</p>
                  </div>
                  <button
                    onClick={() => handleExport('excel')}
                    className="w-full h-[40px] px-3 flex items-center gap-2 hover:bg-[#F3F3F3] rounded-lg text-[14px] text-[#3D3D3D]"
                  >
                    <FileText className="w-4 h-4" />
                    Excel (with gap report)
                  </button>
                  <button
                    onClick={() => handleExport('csv')}
                    className="w-full h-[40px] px-3 flex items-center gap-2 hover:bg-[#F3F3F3] rounded-lg text-[14px] text-[#3D3D3D]"
                  >
                    <FileText className="w-4 h-4" />
                    CSV (raw data)
                  </button>
                  <button
                    onClick={() => handleExport('pdf')}
                    className="w-full h-[40px] px-3 flex items-center gap-2 hover:bg-[#F3F3F3] rounded-lg text-[14px] text-[#3D3D3D]"
                  >
                    <FileText className="w-4 h-4" />
                    PDF (print-ready)
                  </button>
                  <div className="p-3 border-t border-[#DBDBDB] mt-2">
                    <label className="flex items-center gap-2">
                      <input type="checkbox" className="w-4 h-4 accent-[#F36A4F]" />
                      <span className="text-[13px] text-[#3D3D3D]">Include masked PII</span>
                    </label>
                    <label className="flex items-center gap-2 mt-2">
                      <input type="checkbox" className="w-4 h-4 accent-[#F36A4F]" />
                      <span className="text-[13px] text-[#3D3D3D]">Only 80G receipts</span>
                    </label>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
      
      {/* Content Area */}
      <div className="flex-1 overflow-auto p-[24px]">
        {/* Summary Cards */}
        <div className="grid grid-cols-6 gap-[16px] mb-[24px]">
          <div className="bg-white rounded-[16px] border border-[#DBDBDB] p-[16px]">
            <p className="text-[13px] text-[#6E6E6E] mb-1">Total Receipts</p>
            <p className="text-[24px] font-semibold text-[#0D0D0D]">{totalReceipts}</p>
          </div>
          
          <div className="bg-white rounded-[16px] border border-[#DBDBDB] p-[16px]">
            <p className="text-[13px] text-[#6E6E6E] mb-1">Total Amount</p>
            <p className="text-[24px] font-semibold text-[#0D0D0D]">
              ₹{totalAmount.toLocaleString('en-IN')}
            </p>
          </div>
          
          <div className="bg-white rounded-[16px] border border-[#DBDBDB] p-[16px]">
            <p className="text-[13px] text-[#6E6E6E] mb-1">80G Receipts</p>
            <p className="text-[24px] font-semibold text-[#0D0D0D]">{total80GReceipts}</p>
            <p className="text-[12px] text-[#6E6E6E] mt-1">
              ₹{total80GAmount.toLocaleString('en-IN')}
            </p>
          </div>
          
          <div className="bg-white rounded-[16px] border border-[#DBDBDB] p-[16px]">
            <p className="text-[13px] text-[#6E6E6E] mb-1">Online Donations</p>
            <p className="text-[24px] font-semibold text-[#0D0D0D]">
              {mockReceipts.filter(r => r.donationType === 'Online').length}
            </p>
          </div>
          
          <div className="bg-white rounded-[16px] border border-[#DBDBDB] p-[16px]">
            <p className="text-[13px] text-[#6E6E6E] mb-1">Delivery Failures</p>
            <p className="text-[24px] font-semibold text-[#F36A4F]">{deliveryFailures}</p>
          </div>
          
          <div
            className="bg-white rounded-[16px] border-2 border-[#F36A4F] p-[16px] cursor-pointer hover:bg-[#FEF1EE] transition-colors"
            onClick={() => setShowGapDetails(!showGapDetails)}
          >
            <div className="flex items-start justify-between mb-1">
              <p className="text-[13px] text-[#6E6E6E]">Missing Receipts</p>
              <AlertTriangle className="w-4 h-4 text-[#F36A4F]" />
            </div>
            <p className="text-[24px] font-semibold text-[#F36A4F]">
              {missingReceipts.length}
            </p>
            <p className="text-[12px] text-[#6E6E6E] mt-1">Click to view details</p>
          </div>
        </div>
        
        {/* Gap Details Panel */}
        {showGapDetails && (
          <div className="bg-[#FEF1EE] rounded-[16px] border border-[#F36A4F] p-[16px] mb-[24px]">
            <div className="flex items-start justify-between mb-3">
              <div className="flex items-center gap-2">
                <AlertTriangle className="w-5 h-5 text-[#F36A4F]" />
                <h3 className="text-[16px] font-semibold text-[#0D0D0D]">
                  Receipt Sequence Gaps Detected
                </h3>
              </div>
              <button
                onClick={() => setShowGapDetails(false)}
                className="text-[#6E6E6E] hover:text-[#0D0D0D]"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="grid grid-cols-3 gap-[16px] mb-4">
              <div className="bg-white rounded-[12px] p-[12px]">
                <p className="text-[12px] text-[#6E6E6E]">Total in Range</p>
                <p className="text-[20px] font-semibold text-[#0D0D0D]">{totalReceipts + missingReceipts.length}</p>
              </div>
              <div className="bg-white rounded-[12px] p-[12px]">
                <p className="text-[12px] text-[#6E6E6E]">Missing Count</p>
                <p className="text-[20px] font-semibold text-[#F36A4F]">{missingReceipts.length}</p>
              </div>
              <div className="bg-white rounded-[12px] p-[12px]">
                <p className="text-[12px] text-[#6E6E6E]">First Missing</p>
                <p className="text-[14px] font-semibold text-[#0D0D0D]">{missingReceipts[0]}</p>
              </div>
            </div>
            
            <div className="bg-white rounded-[12px] p-[12px]">
              <p className="text-[13px] font-medium text-[#0D0D0D] mb-2">Missing Receipt Numbers:</p>
              <div className="flex flex-wrap gap-2">
                {missingReceipts.map(num => (
                  <div key={num} className="px-3 py-1 bg-[#FEF1EE] rounded-full text-[13px] text-[#F36A4F] font-medium">
                    {num}
                  </div>
                ))}
              </div>
              
              <div className="mt-4 flex gap-2">
                <button className="h-[36px] px-[16px] rounded-full bg-[#F36A4F] hover:bg-[#E55A3F] text-white text-[13px] font-medium">
                  Generate Pending Receipts
                </button>
                <button className="h-[36px] px-[16px] rounded-full border border-[#DBDBDB] hover:bg-[#F3F3F3] text-[#3D3D3D] text-[13px] font-medium">
                  Investigate Gaps
                </button>
              </div>
            </div>
          </div>
        )}
        
        {/* Filters Panel */}
        {showFilters && (
          <div className="bg-white rounded-[16px] border border-[#DBDBDB] p-[16px] mb-[24px]">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-[14px] font-semibold text-[#0D0D0D]">Filters</h3>
              <button className="text-[13px] text-[#F36A4F] hover:text-[#E55A3F] font-medium">
                Reset All
              </button>
            </div>
            
            <div className="grid grid-cols-4 gap-[16px]">
              {/* Date Range */}
              <div>
                <label className="block text-[13px] font-medium text-[#3D3D3D] mb-2">
                  Date Range
                </label>
                <select 
                  defaultValue="This Month"
                  className="w-full h-[44px] px-[12px] rounded-[12px] border border-[#DBDBDB] text-[14px] text-[#3D3D3D] focus:outline-none focus:border-[#F36A4F]"
                >
                  <option>Today</option>
                  <option>This Week</option>
                  <option>This Month</option>
                  <option>This FY</option>
                  <option>Custom Range</option>
                </select>
              </div>
              
              {/* Receipt Type */}
              <div>
                <label className="block text-[13px] font-medium text-[#3D3D3D] mb-2">
                  Receipt Type
                </label>
                <select className="w-full h-[44px] px-[12px] rounded-[12px] border border-[#DBDBDB] text-[14px] text-[#3D3D3D] focus:outline-none focus:border-[#F36A4F]">
                  <option>All Types</option>
                  <option>Online Donation</option>
                  <option>E-Challan</option>
                </select>
              </div>
              
              {/* Status */}
              <div>
                <label className="block text-[13px] font-medium text-[#3D3D3D] mb-2">
                  Status
                </label>
                <select 
                  defaultValue="Generated"
                  className="w-full h-[44px] px-[12px] rounded-[12px] border border-[#DBDBDB] text-[14px] text-[#3D3D3D] focus:outline-none focus:border-[#F36A4F]"
                >
                  <option>All Statuses</option>
                  <option>Generated</option>
                  <option>Pending Generation</option>
                  <option>Cancelled/Reissued</option>
                </select>
              </div>
              
              {/* 80G Filter */}
              <div>
                <label className="block text-[13px] font-medium text-[#3D3D3D] mb-2">
                  80G Eligible
                </label>
                <select 
                  defaultValue="All"
                  className="w-full h-[44px] px-[12px] rounded-[12px] border border-[#DBDBDB] text-[14px] text-[#3D3D3D] focus:outline-none focus:border-[#F36A4F]"
                >
                  <option>All</option>
                  <option>Yes</option>
                  <option>No</option>
                </select>
              </div>
              
              {/* Amount Range */}
              <div>
                <label className="block text-[13px] font-medium text-[#3D3D3D] mb-2">
                  Amount From
                </label>
                <input
                  type="number"
                  placeholder="₹ Min"
                  className="w-full h-[44px] px-[12px] rounded-[12px] border border-[#DBDBDB] text-[14px] text-[#3D3D3D] focus:outline-none focus:border-[#F36A4F]"
                />
              </div>
              
              <div>
                <label className="block text-[13px] font-medium text-[#3D3D3D] mb-2">
                  Amount To
                </label>
                <input
                  type="number"
                  placeholder="₹ Max"
                  className="w-full h-[44px] px-[12px] rounded-[12px] border border-[#DBDBDB] text-[14px] text-[#3D3D3D] focus:outline-none focus:border-[#F36A4F]"
                />
              </div>
              
              {/* Category Filter */}
              <div>
                <label className="block text-[13px] font-medium text-[#3D3D3D] mb-2">
                  Donation Category
                </label>
                <select className="w-full h-[44px] px-[12px] rounded-[12px] border border-[#DBDBDB] text-[14px] text-[#3D3D3D] focus:outline-none focus:border-[#F36A4F]">
                  <option>All Categories</option>
                  <option>General Donation</option>
                  <option>Education Fund</option>
                  <option>Health & Medical</option>
                  <option>Infrastructure</option>
                </select>
              </div>
              
              {/* Payment Method */}
              <div>
                <label className="block text-[13px] font-medium text-[#3D3D3D] mb-2">
                  Payment Method
                </label>
                <select className="w-full h-[44px] px-[12px] rounded-[12px] border border-[#DBDBDB] text-[14px] text-[#3D3D3D] focus:outline-none focus:border-[#F36A4F]">
                  <option>All Methods</option>
                  <option>UPI</option>
                  <option>Card</option>
                  <option>Netbanking</option>
                  <option>Wallet</option>
                  <option>Bank Transfer</option>
                  <option>Cheque</option>
                </select>
              </div>
            </div>
            
            {/* Advanced Filters Toggle */}
            <div className="mt-4 pt-4 border-t border-[#DBDBDB]">
              <button className="flex items-center gap-2 text-[13px] text-[#F36A4F] hover:text-[#E55A3F] font-medium">
                <ChevronRight className="w-4 h-4" />
                Show Advanced Filters (Donor, Payment Gateway, Refund Status)
              </button>
            </div>
          </div>
        )}
        
        {/* Column Configuration Panel */}
        {showColumnConfig && (
          <div className="bg-white rounded-[16px] border border-[#DBDBDB] p-[16px] mb-[24px]">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-[14px] font-semibold text-[#0D0D0D]">Column Configuration</h3>
              <button
                onClick={() => setShowColumnConfig(false)}
                className="text-[#6E6E6E] hover:text-[#0D0D0D]"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="grid grid-cols-4 gap-[12px]">
              {COLUMN_OPTIONS.map(col => (
                <label key={col.id} className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={visibleColumns.includes(col.id)}
                    onChange={() => handleColumnToggle(col.id)}
                    className="w-4 h-4 accent-[#F36A4F]"
                  />
                  <span className="text-[13px] text-[#3D3D3D]">
                    {col.label}
                    {col.core && <span className="text-[#F36A4F] ml-1">*</span>}
                  </span>
                </label>
              ))}
            </div>
            
            <p className="text-[12px] text-[#6E6E6E] mt-3">
              * Core columns recommended for compliance
            </p>
          </div>
        )}
        
        {/* Search Bar */}
        <div className="bg-white rounded-[16px] border border-[#DBDBDB] p-[16px] mb-[16px]">
          <div className="flex items-center gap-2">
            <Search className="w-5 h-5 text-[#6E6E6E]" />
            <input
              type="text"
              placeholder="Search by receipt number, donor name, PAN, email, mobile..."
              className="flex-1 text-[14px] text-[#3D3D3D] focus:outline-none"
            />
          </div>
        </div>
        
        {/* Data Table */}
        <div className="bg-white rounded-[16px] border border-[#DBDBDB] overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="bg-[#F8F8F8] border-b border-[#DBDBDB]">
                  <th className="h-[48px] px-[16px] text-left text-[13px] font-semibold text-[#3D3D3D]">
                    Receipt No
                  </th>
                  <th className="h-[48px] px-[16px] text-left text-[13px] font-semibold text-[#3D3D3D]">
                    Receipt Date
                  </th>
                  <th className="h-[48px] px-[16px] text-left text-[13px] font-semibold text-[#3D3D3D]">
                    Donor Name
                  </th>
                  {visibleColumns.includes('pan') && (
                    <th className="h-[48px] px-[16px] text-left text-[13px] font-semibold text-[#3D3D3D]">
                      PAN
                    </th>
                  )}
                  <th className="h-[48px] px-[16px] text-right text-[13px] font-semibold text-[#3D3D3D]">
                    Amount
                  </th>
                  {visibleColumns.includes('category') && (
                    <th className="h-[48px] px-[16px] text-left text-[13px] font-semibold text-[#3D3D3D]">
                      Category
                    </th>
                  )}
                  {visibleColumns.includes('is80G') && (
                    <th className="h-[48px] px-[16px] text-center text-[13px] font-semibold text-[#3D3D3D]">
                      80G
                    </th>
                  )}
                  {visibleColumns.includes('status') && (
                    <th className="h-[48px] px-[16px] text-left text-[13px] font-semibold text-[#3D3D3D]">
                      Status
                    </th>
                  )}
                  {visibleColumns.includes('deliveryStatus') && (
                    <th className="h-[48px] px-[16px] text-center text-[13px] font-semibold text-[#3D3D3D]">
                      Delivery
                    </th>
                  )}
                  <th className="h-[48px] px-[16px] text-right text-[13px] font-semibold text-[#3D3D3D]">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody>
                {mockReceipts.map((receipt, index) => (
                  <tr
                    key={receipt.id}
                    className="border-b border-[#DBDBDB] hover:bg-[#F8F8F8] transition-colors"
                  >
                    <td className="h-[56px] px-[16px] text-[14px] text-[#0D0D0D] font-medium">
                      {receipt.receiptNo}
                    </td>
                    <td className="h-[56px] px-[16px] text-[14px] text-[#3D3D3D]">
                      {new Date(receipt.receiptDate).toLocaleDateString('en-IN', {
                        day: '2-digit',
                        month: 'short',
                        year: 'numeric',
                      })}
                    </td>
                    <td className="h-[56px] px-[16px] text-[14px] text-[#3D3D3D]">
                      {receipt.donorName}
                    </td>
                    {visibleColumns.includes('pan') && (
                      <td className="h-[56px] px-[16px] text-[14px] text-[#3D3D3D] font-mono">
                        {receipt.pan}
                      </td>
                    )}
                    <td className="h-[56px] px-[16px] text-[14px] text-[#0D0D0D] font-semibold text-right">
                      ₹{receipt.amount.toLocaleString('en-IN')}
                    </td>
                    {visibleColumns.includes('category') && (
                      <td className="h-[56px] px-[16px] text-[14px] text-[#3D3D3D]">
                        {receipt.category}
                      </td>
                    )}
                    {visibleColumns.includes('is80G') && (
                      <td className="h-[56px] px-[16px] text-center">
                        {receipt.is80G ? (
                          <span className="inline-block px-2 py-1 bg-[#E8F5E9] text-[#2E7D32] text-[12px] font-medium rounded-full">
                            Yes
                          </span>
                        ) : (
                          <span className="inline-block px-2 py-1 bg-[#F3F3F3] text-[#6E6E6E] text-[12px] font-medium rounded-full">
                            No
                          </span>
                        )}
                      </td>
                    )}
                    {visibleColumns.includes('status') && (
                      <td className="h-[56px] px-[16px]">
                        <span
                          className={`inline-block px-2 py-1 text-[12px] font-medium rounded-full ${
                            receipt.status === 'Generated'
                              ? 'bg-[#E8F5E9] text-[#2E7D32]'
                              : 'bg-[#FFF3E0] text-[#E65100]'
                          }`}
                        >
                          {receipt.status}
                        </span>
                      </td>
                    )}
                    {visibleColumns.includes('deliveryStatus') && (
                      <td className="h-[56px] px-[16px]">
                        <div className="flex items-center justify-center gap-2">
                          <div
                            className={`w-6 h-6 rounded-full flex items-center justify-center ${
                              receipt.deliveryStatus.email === 'sent'
                                ? 'bg-[#E8F5E9]'
                                : receipt.deliveryStatus.email === 'failed'
                                ? 'bg-[#FFEBEE]'
                                : 'bg-[#F3F3F3]'
                            }`}
                          >
                            <Mail
                              className={`w-3 h-3 ${
                                receipt.deliveryStatus.email === 'sent'
                                  ? 'text-[#2E7D32]'
                                  : receipt.deliveryStatus.email === 'failed'
                                  ? 'text-[#C62828]'
                                  : 'text-[#6E6E6E]'
                              }`}
                            />
                          </div>
                          <div
                            className={`w-6 h-6 rounded-full flex items-center justify-center ${
                              receipt.deliveryStatus.sms === 'sent'
                                ? 'bg-[#E8F5E9]'
                                : receipt.deliveryStatus.sms === 'failed'
                                ? 'bg-[#FFEBEE]'
                                : 'bg-[#F3F3F3]'
                            }`}
                          >
                            <MessageSquare
                              className={`w-3 h-3 ${
                                receipt.deliveryStatus.sms === 'sent'
                                  ? 'text-[#2E7D32]'
                                  : receipt.deliveryStatus.sms === 'failed'
                                  ? 'text-[#C62828]'
                                  : 'text-[#6E6E6E]'
                              }`}
                            />
                          </div>
                        </div>
                      </td>
                    )}
                    <td className="h-[56px] px-[16px]">
                      <div className="flex items-center justify-end gap-2">
                        <button
                          onClick={() => handleViewAudit(receipt)}
                          className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-[#F3F3F3] transition-colors"
                          title="View PDF"
                        >
                          <Eye className="w-4 h-4 text-[#3D3D3D]" />
                        </button>
                        {receipt.status === 'Generated' && (
                          <>
                            {receipt.deliveryStatus.email === 'failed' && (
                              <button
                                onClick={() => handleResend('email', receipt)}
                                className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-[#F3F3F3] transition-colors"
                                title="Resend Email"
                              >
                                <Mail className="w-4 h-4 text-[#F36A4F]" />
                              </button>
                            )}
                            {receipt.deliveryStatus.sms === 'failed' && (
                              <button
                                onClick={() => handleResend('sms', receipt)}
                                className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-[#F3F3F3] transition-colors"
                                title="Resend SMS"
                              >
                                <MessageSquare className="w-4 h-4 text-[#F36A4F]" />
                              </button>
                            )}
                            <button
                              onClick={() => handleRegenerate(receipt)}
                              className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-[#F3F3F3] transition-colors"
                              title="Regenerate PDF"
                            >
                              <RotateCcw className="w-4 h-4 text-[#3D3D3D]" />
                            </button>
                          </>
                        )}
                        <button
                          onClick={() => handleViewAudit(receipt)}
                          className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-[#F3F3F3] transition-colors"
                          title="View Audit Trail"
                        >
                          <History className="w-4 h-4 text-[#3D3D3D]" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          
          {/* Pagination */}
          <div className="h-[64px] px-[16px] flex items-center justify-between border-t border-[#DBDBDB]">
            <p className="text-[13px] text-[#6E6E6E]">
              Showing 1 to {mockReceipts.length} of {mockReceipts.length} receipts
            </p>
            <div className="flex items-center gap-2">
              <button className="h-[36px] px-[16px] rounded-full border border-[#DBDBDB] hover:bg-[#F3F3F3] text-[13px] font-medium text-[#3D3D3D]">
                Previous
              </button>
              <button className="h-[36px] w-[36px] rounded-full bg-[#F36A4F] text-white text-[13px] font-medium">
                1
              </button>
              <button className="h-[36px] px-[16px] rounded-full border border-[#DBDBDB] hover:bg-[#F3F3F3] text-[13px] font-medium text-[#3D3D3D]">
                Next
              </button>
            </div>
          </div>
        </div>
      </div>
      
      {/* Reason Modal */}
      {showReasonModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-[16px] w-[480px] p-[24px]">
            <h3 className="text-[18px] font-semibold text-[#0D0D0D] mb-4">
              {reasonAction} - Reason Required
            </h3>
            
            <div className="mb-4">
              <label className="block text-[13px] font-medium text-[#3D3D3D] mb-2">
                Receipt Number
              </label>
              <p className="text-[14px] text-[#6E6E6E]">{selectedReceipt?.receiptNo}</p>
            </div>
            
            <div className="mb-6">
              <label className="block text-[13px] font-medium text-[#3D3D3D] mb-2">
                Reason *
              </label>
              <textarea
                className="w-full h-[100px] px-[12px] py-[10px] rounded-[12px] border border-[#DBDBDB] text-[14px] text-[#3D3D3D] focus:outline-none focus:border-[#F36A4F] resize-none"
                placeholder="Enter reason for this action..."
              />
            </div>
            
            <div className="flex justify-end gap-3">
              <button
                onClick={() => {
                  setShowReasonModal(false);
                  setSelectedReceipt(null);
                }}
                className="h-[44px] px-[20px] rounded-full border border-[#DBDBDB] hover:bg-[#F3F3F3] text-[14px] font-medium text-[#3D3D3D]"
              >
                Cancel
              </button>
              <button className="h-[44px] px-[20px] rounded-full bg-[#F36A4F] hover:bg-[#E55A3F] text-white text-[14px] font-medium">
                Confirm & Proceed
              </button>
            </div>
          </div>
        </div>
      )}
      
      {/* Audit Trail Drawer */}
      {showAuditTrail && (
        <div className="fixed inset-0 bg-black/50 flex items-end justify-end z-50">
          <div className="bg-white w-[480px] h-full overflow-auto">
            <div className="sticky top-0 bg-white border-b border-[#DBDBDB] p-[24px] flex items-center justify-between">
              <div>
                <h3 className="text-[18px] font-semibold text-[#0D0D0D]">
                  Audit Trail
                </h3>
                <p className="text-[13px] text-[#6E6E6E] mt-1">
                  {selectedReceipt?.receiptNo}
                </p>
              </div>
              <button
                onClick={() => {
                  setShowAuditTrail(false);
                  setSelectedReceipt(null);
                }}
                className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-[#F3F3F3]"
              >
                <X className="w-5 h-5 text-[#3D3D3D]" />
              </button>
            </div>
            
            <div className="p-[24px]">
              {/* Receipt Details */}
              <div className="bg-[#F8F8F8] rounded-[12px] p-[16px] mb-6">
                <h4 className="text-[14px] font-semibold text-[#0D0D0D] mb-3">
                  Receipt Details
                </h4>
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <span className="text-[13px] text-[#6E6E6E]">Donor:</span>
                    <span className="text-[13px] text-[#0D0D0D] font-medium">
                      {selectedReceipt?.donorName}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[13px] text-[#6E6E6E]">Amount:</span>
                    <span className="text-[13px] text-[#0D0D0D] font-medium">
                      ₹{selectedReceipt?.amount.toLocaleString('en-IN')}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[13px] text-[#6E6E6E]">Category:</span>
                    <span className="text-[13px] text-[#0D0D0D] font-medium">
                      {selectedReceipt?.category}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[13px] text-[#6E6E6E]">Template:</span>
                    <span className="text-[13px] text-[#0D0D0D] font-medium">
                      {selectedReceipt?.templateVersion}
                    </span>
                  </div>
                </div>
              </div>
              
              {/* Audit Events */}
              <h4 className="text-[14px] font-semibold text-[#0D0D0D] mb-3">
                Activity Timeline
              </h4>
              
              <div className="space-y-3">
                <div className="flex gap-3">
                  <div className="w-8 h-8 rounded-full bg-[#E8F5E9] flex items-center justify-center flex-shrink-0">
                    <FileText className="w-4 h-4 text-[#2E7D32]" />
                  </div>
                  <div className="flex-1">
                    <p className="text-[13px] font-medium text-[#0D0D0D]">
                      Receipt Generated
                    </p>
                    <p className="text-[12px] text-[#6E6E6E] mt-1">
                      Generated by {selectedReceipt?.generatedBy}
                    </p>
                    <p className="text-[12px] text-[#6E6E6E]">
                      {selectedReceipt?.generatedOn}
                    </p>
                  </div>
                </div>
                
                <div className="flex gap-3">
                  <div className="w-8 h-8 rounded-full bg-[#E3F2FD] flex items-center justify-center flex-shrink-0">
                    <Mail className="w-4 h-4 text-[#1976D2]" />
                  </div>
                  <div className="flex-1">
                    <p className="text-[13px] font-medium text-[#0D0D0D]">
                      Email Sent
                    </p>
                    <p className="text-[12px] text-[#6E6E6E] mt-1">
                      Sent to {selectedReceipt?.email}
                    </p>
                    <p className="text-[12px] text-[#6E6E6E]">
                      {selectedReceipt?.generatedOn}
                    </p>
                  </div>
                </div>
                
                <div className="flex gap-3">
                  <div className="w-8 h-8 rounded-full bg-[#E3F2FD] flex items-center justify-center flex-shrink-0">
                    <MessageSquare className="w-4 h-4 text-[#1976D2]" />
                  </div>
                  <div className="flex-1">
                    <p className="text-[13px] font-medium text-[#0D0D0D]">
                      SMS Sent
                    </p>
                    <p className="text-[12px] text-[#6E6E6E] mt-1">
                      Sent to {selectedReceipt?.mobile}
                    </p>
                    <p className="text-[12px] text-[#6E6E6E]">
                      {selectedReceipt?.generatedOn}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}