import { z } from 'zod';
export declare const optional: z.ZodOptional<z.ZodString>;
export declare const optional_boolean: z.ZodOptional<z.ZodBoolean>;
export declare const simple_boolean: z.ZodOptional<z.ZodBoolean>;
export declare const simple_email: z.ZodString;
export declare const simple_password_login: z.ZodString;
export declare const simple_password: z.ZodString;
export declare const simple_retype_password: z.ZodString;
export declare const simple_first_name: z.ZodString;
export declare const z_email_name: z.ZodString;
export declare const simple_name: z.ZodString;
export declare const simple_last_name: z.ZodString;
export declare const simple_user_type: z.ZodString;
export declare const simple_location: z.ZodString;
export declare const contract_date: z.ZodEffects<z.ZodOptional<z.ZodDate>, Date | undefined, unknown>;
export declare const contract_amount: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>;
export declare const simple_phone: z.ZodEffects<z.ZodString, string, string>;
export declare const expiration_date: z.ZodEffects<z.ZodOptional<z.ZodDate>, Date | undefined, unknown>;
export declare const simple_file_upload: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodType<File, z.ZodTypeDef, File>>, File | undefined, File | undefined>, File | undefined, File | undefined>;
//# sourceMappingURL=zod.validator.d.ts.map