import { Injectable, Inject, NotFoundException } from '@nestjs/common';
import { DRIZZLE } from '../../database/database.module';
import { receiptSettings } from '../../database/models/receipt-settings.model';
import { auditLog } from '../../database/models/audit-log.model';
import { eq } from 'drizzle-orm';
import type { NodeMsSqlDatabase } from 'drizzle-orm/node-mssql';
import * as schema from '../../database/schema';
import type { UpdateReceiptSettingsDto } from './dto/update-receipt-settings.dto';

const FIXED_RECEIPT_PREFIX = 'ARAM/2025-26/';

@Injectable()
export class ReceiptSettingsService {
  constructor(@Inject(DRIZZLE) private db: NodeMsSqlDatabase<typeof schema>) { }

  async findSettings() {
    const rows = await this.db.select().top(1).from(receiptSettings);

    if (rows.length === 0) {
      // Return default settings if none exist
      return this.getDefaultSettings();
    }

    const row = rows[0];
    return this.parseSettings(row);
  }

  async updateSettings(dto: UpdateReceiptSettingsDto) {
    const existing = await this.db.select().top(1).from(receiptSettings);

    const updates: Record<string, unknown> = {
      updatedAt: new Date(),
      updatedBy: dto.updatedBy || 'System',
    };

    // Numbering & Series
    if (dto.receiptTypes !== undefined) updates.receiptTypesJson = JSON.stringify(dto.receiptTypes);
    if (dto.paddingLength !== undefined) updates.paddingLength = dto.paddingLength;
    if (dto.noGapEnforcement !== undefined) updates.noGapEnforcement = dto.noGapEnforcement;
    if (dto.autoCreateNewSeries !== undefined) updates.autoCreateNewSeries = dto.autoCreateNewSeries;
    if (dto.manualApprovalRequired !== undefined) updates.manualApprovalRequired = dto.manualApprovalRequired;
    if (dto.receiptTypes !== undefined) updates.receiptTypesJson = JSON.stringify(dto.receiptTypes);

    // Handle receiptPrefix and startingNumber (stored in configJson)
    if (dto.receiptPrefix !== undefined || dto.startingNumber !== undefined) {
      let currentConfig: any = {};
      try {
        currentConfig = existing.length > 0 && existing[0].configJson
          ? JSON.parse(existing[0].configJson)
          : {};
      } catch {
        currentConfig = {};
      }

      if (dto.receiptPrefix !== undefined) currentConfig.receiptPrefix = dto.receiptPrefix;
      if (dto.startingNumber !== undefined) currentConfig.startingNumber = dto.startingNumber;

      updates.configJson = JSON.stringify(currentConfig);
    }

    // Generation Rules
    // Generation Rules removed




    // Mandatory Fields
    if (dto.mobileRequired !== undefined) updates.mobileRequired = dto.mobileRequired;
    if (dto.emailRequired !== undefined) updates.emailRequired = dto.emailRequired;
    if (dto.addressRequired !== undefined) updates.addressRequired = dto.addressRequired;
    if (dto.donationCategoryRequired !== undefined) updates.donationCategoryRequired = dto.donationCategoryRequired;
    if (dto.donationTypeRequired !== undefined) updates.donationTypeRequired = dto.donationTypeRequired;
    if (dto.panRule !== undefined) updates.panRule = dto.panRule;
    if (dto.panThreshold !== undefined) updates.panThreshold = dto.panThreshold;
    if (dto.panAutoUppercase !== undefined) updates.panAutoUppercase = dto.panAutoUppercase;


    // Delivery Settings
    if (dto.autoSendEmailOnReceiptGeneration !== undefined) updates.autoSendEmailOnReceiptGeneration = dto.autoSendEmailOnReceiptGeneration;
    if (dto.emailSubjectFormat !== undefined) updates.emailSubjectFormat = dto.emailSubjectFormat;
    if (dto.emailSenderName !== undefined) updates.emailSenderName = dto.emailSenderName;
    if (dto.emailReplyTo !== undefined) updates.emailReplyTo = dto.emailReplyTo;

    if (dto.emailFailureAlertsNotifyAdmin !== undefined) updates.emailFailureAlertsNotifyAdmin = dto.emailFailureAlertsNotifyAdmin;
    if (dto.autoSendSmsOnReceiptGeneration !== undefined) updates.autoSendSmsOnReceiptGeneration = dto.autoSendSmsOnReceiptGeneration;
    if (dto.smsShortLink !== undefined) updates.smsShortLink = dto.smsShortLink;


    // Reprint & Reissue
    if (dto.allowReprint !== undefined) updates.allowReprint = dto.allowReprint;
    if (dto.allowResendEmail !== undefined) updates.allowResendEmail = dto.allowResendEmail;
    if (dto.allowCorrection !== undefined) updates.allowCorrection = dto.allowCorrection;
    if (dto.requireReasonReprint !== undefined) updates.requireReasonReprint = dto.requireReasonReprint;
    if (dto.requireReasonCorrection !== undefined) updates.requireReasonCorrection = dto.requireReasonCorrection;
    if (dto.requireReasonManualGen !== undefined) updates.requireReasonManualGen = dto.requireReasonManualGen;


    if (existing.length === 0) {
      // Insert new settings (id is auto-generated by IDENTITY column)
      await this.db.insert(receiptSettings).values({
        ...updates,
        createdAt: new Date(),
      } as any);
    } else {
      // Update existing settings
      await this.db.update(receiptSettings).set(updates).where(eq(receiptSettings.id, existing[0].id));
    }

    // Log to audit trail if reasonForChange is provided
    if (dto.reasonForChange) {
      await this.db.insert(auditLog).values({
        userId: null, // Could be extracted from JWT token if available
        action: 'UPDATE_RECEIPT_SETTINGS',
        entityType: 'receipt_settings',
        entityId: existing.length > 0 ? String(existing[0].id) : '1',
        detailsJson: JSON.stringify({
          reason: dto.reasonForChange,
          updatedBy: dto.updatedBy || 'System',
          timestamp: new Date().toISOString(),
        }),
        ipAddress: null, // Could be extracted from request if available
      } as any);
    }

    return this.findSettings();
  }

  private parseSettings(row: any) {
    let receiptTypes: any[] = [];
    if (row.receiptTypesJson) {
      try {
        receiptTypes = JSON.parse(row.receiptTypesJson);
      } catch {
        // ignore
      }
    }

    let config: any = {};
    if (row.configJson) {
      try {
        config = JSON.parse(row.configJson);
      } catch {
        // ignore
      }
    }

    return {
      id: row.id,
      // Numbering & Series
      receiptPrefix: config.receiptPrefix || '',
      startingNumber: config.startingNumber || '1',
      paddingLength: row.paddingLength,
      noGapEnforcement: row.noGapEnforcement,
      autoCreateNewSeries: row.autoCreateNewSeries,
      manualApprovalRequired: row.manualApprovalRequired,
      receiptTypes,
      // Generation Rules
      autoGenerateOnSuccess: row.autoGenerateOnSuccess,
      generationDelay: row.generationDelay,
      autoGenerateImports: row.autoGenerateImports,
      allowManualOffline: row.allowManualOffline,
      allowManualBulk: row.allowManualBulk,
      allowBackdated: row.allowBackdated,
      backdateWindow: row.backdateWindow,
      showBackdateStamp: row.showBackdateStamp,
      requireReasonManual: row.requireReasonManual,

      // Mandatory Fields
      mobileRequired: row.mobileRequired,
      emailRequired: row.emailRequired,
      addressRequired: row.addressRequired,
      donationCategoryRequired: row.donationCategoryRequired,
      donationTypeRequired: row.donationTypeRequired,
      panRule: row.panRule,
      panThreshold: row.panThreshold,
      panAutoUppercase: row.panAutoUppercase,

      // Delivery Settings
      autoSendEmailOnReceiptGeneration: row.autoSendEmailOnReceiptGeneration,
      emailSubjectFormat: row.emailSubjectFormat,
      emailSenderName: row.emailSenderName,
      emailReplyTo: row.emailReplyTo,

      emailFailureAlertsNotifyAdmin: row.emailFailureAlertsNotifyAdmin,
      autoSendSmsOnReceiptGeneration: row.autoSendSmsOnReceiptGeneration,
      smsShortLink: row.smsShortLink,

      // Reprint & Reissue
      allowReprint: row.allowReprint,
      allowResendEmail: row.allowResendEmail,
      allowCorrection: row.allowCorrection,
      requireReasonReprint: row.requireReasonReprint,
      requireReasonCorrection: row.requireReasonCorrection,
      requireReasonManualGen: row.requireReasonManualGen,
      requireReasonRegenerate: row.requireReasonRegenerate,
      requireReasonCancel: row.requireReasonCancel,
      // Metadata
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
      updatedBy: row.updatedBy,
    };
  }

  private getDefaultSettings() {
    return {
      id: null,
      // Numbering & Series (Stored in configJson)
      configJson: JSON.stringify({
        receiptPrefix: 'ARAM/2025-26/',
        startingNumber: '1',
      }),
      paddingLength: 5,
      noGapEnforcement: true,
      autoCreateNewSeries: true,
      manualApprovalRequired: false,
      receiptTypes: [
        { id: 'online', label: 'Online Donation', enabled: true, isDefault: true },
        { id: 'echallan_cash', label: 'E-Challan (Cash)', enabled: true, isDefault: false },
        { id: 'echallan_cheque', label: 'E-Challan (Cheque)', enabled: true, isDefault: false },
        { id: 'echallan_dd', label: 'E-Challan (DD)', enabled: true, isDefault: false },
        { id: 'echallan_bank', label: 'E-Challan (Bank Transfer)', enabled: true, isDefault: false },
      ],
      // Generation Rules
      autoGenerateOnSuccess: true,
      generationDelay: 0,
      autoGenerateImports: false,
      allowManualOffline: true,
      allowManualBulk: true,
      allowBackdated: true,
      backdateWindow: 30,
      showBackdateStamp: true,
      requireReasonManual: true,

      // Mandatory Fields
      mobileRequired: true,
      emailRequired: true,
      addressRequired: false,
      donationCategoryRequired: true,
      donationTypeRequired: true,
      panRule: 'threshold',
      panThreshold: 2000,
      panAutoUppercase: true,

      // Delivery Settings
      autoSendEmailOnReceiptGeneration: true,
      emailSubjectFormat: 'Your donation receipt {receipt_no} - Aram Foundation',
      emailSenderName: 'Aram Foundation',
      emailReplyTo: 'donations@aramfoundation.org',

      emailFailureAlertsNotifyAdmin: true,
      autoSendSmsOnReceiptGeneration: false,
      smsShortLink: true,

      // Reprint & Reissue
      allowReprint: true,
      allowResendEmail: true,
      allowCorrection: true,
      requireReasonReprint: false,
      requireReasonCorrection: true,
      requireReasonManualGen: true,
      requireReasonRegenerate: true,
      requireReasonCancel: true,
      // Metadata
      createdAt: null,
      updatedAt: null,
      updatedBy: null,
    };
  }

  /**
   * Generates the next sequential receipt number based on current settings.
   * Atomically updates the 'startingNumber' in the database.
   */
  async generateNextReceiptNumber(categoryId?: number): Promise<string> {
    return await this.db.transaction(async (tx) => {
      // 1. Lock & Get Settings
      const rows = await tx.select().from(receiptSettings);
      let settings = rows[0];

      if (!settings) {
        // Create defaults if they don't exist
        const defaultSettings = this.getDefaultSettings();
        // Remove ID and metadata to insert
        const { id, createdAt, updatedAt, updatedBy, receiptTypes, ...toInsert } = defaultSettings;

        await tx.insert(receiptSettings).values({
          ...toInsert,
          receiptTypesJson: JSON.stringify(receiptTypes),
          createdAt: new Date(),
        } as any);

        const newRows = await tx.select().from(receiptSettings);
        settings = newRows[0];
      }

      // 2. Generate Number from configJson
      let config: any = {};
      try {
        config = settings.configJson ? JSON.parse(settings.configJson) : {};
      } catch {
        config = {};
      }

      // Use fixed prefix as requested by user
      const prefix = FIXED_RECEIPT_PREFIX;
      const currentSeqStr = config.startingNumber || '1';
      const padding = settings.paddingLength || 5;

      // Convert to integer
      let currentSeq = parseInt(currentSeqStr, 10);
      if (isNaN(currentSeq)) currentSeq = 1;

      const items = String(currentSeq).padStart(padding, '0');

      // Handle conditional spacing based on noGapEnforcement
      // If true: "ARAM / 2025-26 / 00001"
      // If false: "ARAM/2025-26/00001"
      let fullReceiptNumber = `${prefix}${items}`;
      if (settings.noGapEnforcement) {
        fullReceiptNumber = fullReceiptNumber.replace(/\//g, ' / ');
      }

      // 3. Increment for next time
      const nextSeq = currentSeq + 1;
      const nextSeqStr = String(nextSeq).padStart(currentSeqStr.length, '0');

      config.startingNumber = nextSeqStr;

      await tx
        .update(receiptSettings)
        .set({ configJson: JSON.stringify(config) })
        .where(eq(receiptSettings.id, settings.id));

      return fullReceiptNumber;
    });
  }
}
