//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Challan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SaiAramFoundationEntities : DbContext
    {
        public SaiAramFoundationEntities()
            : base("name=SaiAramFoundationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_BASIC_SETTING> T_BASIC_SETTING { get; set; }
        public DbSet<T_CFG_ERRORLOG> T_CFG_ERRORLOG { get; set; }
        public DbSet<T_CFG_Recipients> T_CFG_Recipients { get; set; }
        public DbSet<T_Country> T_Country { get; set; }
        public DbSet<T_DONOR_CATEGORIES> T_DONOR_CATEGORIES { get; set; }
        public DbSet<T_EChallan> T_EChallan { get; set; }
        public DbSet<T_Payment_Gateway_Config> T_Payment_Gateway_Config { get; set; }
        public DbSet<T_Payment_Order_No> T_Payment_Order_No { get; set; }
        public DbSet<T_Payment_Transaction> T_Payment_Transaction { get; set; }
        public DbSet<T_Razorpay_Transaction> T_Razorpay_Transaction { get; set; }
        public DbSet<T_State> T_State { get; set; }
        public DbSet<T_USER> T_USER { get; set; }
        public DbSet<T_User_Activites> T_User_Activites { get; set; }
        public DbSet<All_PGI_Data638> All_PGI_Data638 { get; set; }
    
        [EdmFunction("SaiAramFoundationEntities", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string str, string separator)
        {
            var strParameter = str != null ?
                new ObjectParameter("str", str) :
                new ObjectParameter("str", typeof(string));
    
            var separatorParameter = separator != null ?
                new ObjectParameter("separator", separator) :
                new ObjectParameter("separator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[SaiAramFoundationEntities].[SplitString](@str, @separator)", strParameter, separatorParameter);
        }
    
        public virtual ObjectResult<FundCollectionMonthwiseWithParameters_Result> FundCollectionMonthwiseWithParameters(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FundCollectionMonthwiseWithParameters_Result>("FundCollectionMonthwiseWithParameters", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<sp_FundCollection_Below_Result> sp_FundCollection_Below()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FundCollection_Below_Result>("sp_FundCollection_Below");
        }
    
        public virtual ObjectResult<sp_FundCollection_DateOnly_Result> sp_FundCollection_DateOnly()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FundCollection_DateOnly_Result>("sp_FundCollection_DateOnly");
        }
    
        public virtual ObjectResult<sp_FundCollectionMonthwise_Result> sp_FundCollectionMonthwise()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FundCollectionMonthwise_Result>("sp_FundCollectionMonthwise");
        }
    
        public virtual int sp_GetCashDatewise()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetCashDatewise");
        }
    
        public virtual int sp_GetCashFunds(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetCashFunds", fromdateParameter, todateParameter);
        }
    
        public virtual int sp_GetDDChequeDatewise()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetDDChequeDatewise");
        }
    
        public virtual int sp_GetDDChequeFunds(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetDDChequeFunds", fromdateParameter, todateParameter);
        }
    
        public virtual ObjectResult<sp_GetFundCollectionReport_Result> sp_GetFundCollectionReport(Nullable<int> donorType, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var donorTypeParameter = donorType.HasValue ?
                new ObjectParameter("DonorType", donorType) :
                new ObjectParameter("DonorType", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetFundCollectionReport_Result>("sp_GetFundCollectionReport", donorTypeParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<sp_GetLogHistory_Result> sp_GetLogHistory(string searchKey)
        {
            var searchKeyParameter = searchKey != null ?
                new ObjectParameter("SearchKey", searchKey) :
                new ObjectParameter("SearchKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetLogHistory_Result>("sp_GetLogHistory", searchKeyParameter);
        }
    
        public virtual ObjectResult<sp_GetReceiptDatewise_Result> sp_GetReceiptDatewise(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetReceiptDatewise_Result>("sp_GetReceiptDatewise", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<sp_GetReceiptDt_Result> sp_GetReceiptDt(string searchKey)
        {
            var searchKeyParameter = searchKey != null ?
                new ObjectParameter("SearchKey", searchKey) :
                new ObjectParameter("SearchKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetReceiptDt_Result>("sp_GetReceiptDt", searchKeyParameter);
        }
    
        public virtual ObjectResult<sp_GetReceiptDt_By_ID_Result> sp_GetReceiptDt_By_ID(string strId, Nullable<int> intLoginId)
        {
            var strIdParameter = strId != null ?
                new ObjectParameter("strId", strId) :
                new ObjectParameter("strId", typeof(string));
    
            var intLoginIdParameter = intLoginId.HasValue ?
                new ObjectParameter("intLoginId", intLoginId) :
                new ObjectParameter("intLoginId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetReceiptDt_By_ID_Result>("sp_GetReceiptDt_By_ID", strIdParameter, intLoginIdParameter);
        }
    
        public virtual ObjectResult<sp_GetReceiptDt_By_Online_Result> sp_GetReceiptDt_By_Online(Nullable<int> intId)
        {
            var intIdParameter = intId.HasValue ?
                new ObjectParameter("intId", intId) :
                new ObjectParameter("intId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetReceiptDt_By_Online_Result>("sp_GetReceiptDt_By_Online", intIdParameter);
        }
    
        public virtual ObjectResult<sp_GetSettings_Result> sp_GetSettings()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSettings_Result>("sp_GetSettings");
        }
    
        public virtual ObjectResult<SP_PGI_UsedColumns_Result> SP_PGI_UsedColumns()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PGI_UsedColumns_Result>("SP_PGI_UsedColumns");
        }
    }
}
