//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Challan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BASIC_SETTING
    {
        public int Id { get; set; }
        public string Aram_MailId { get; set; }
        public string Aram_ReplyTo_MailId { get; set; }
        public string Aram_CC_MailId { get; set; }
        public string Aram_BCC_MailId { get; set; }
        public string Aram_Mail_Subject { get; set; }
        public Nullable<System.DateTime> Service_StartDate { get; set; }
        public Nullable<System.DateTime> Service_EndDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Aram_Mail_Body_1 { get; set; }
    }
}
