//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Challan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CFG_ERRORLOG
    {
        public long Error_ID { get; set; }
        public string ProjectName { get; set; }
        public string FormName { get; set; }
        public string CustomerID { get; set; }
        public string ProcessName { get; set; }
        public string Severity { get; set; }
        public string ErrorDetails { get; set; }
        public string UserName { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<System.DateTime> Data_Date { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
