//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Challan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CFG_Recipients
    {
        public int Id { get; set; }
        public long Institution_Id { get; set; }
        public string Email_Type { get; set; }
        public string Recipient_Type { get; set; }
        public string FromEmail { get; set; }
        public string ToEmails { get; set; }
        public string BCCs { get; set; }
        public string CCs { get; set; }
        public string Subject { get; set; }
        public string Signature { get; set; }
        public string Body { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Delete_Flag { get; set; }
    }
}
