//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Challan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EChallan
    {
        public int Id { get; set; }
        public string Receipt_Number { get; set; }
        public int Donation_Types { get; set; }
        public string Account_Number { get; set; }
        public string Name_Of_Donor { get; set; }
        public string Address { get; set; }
        public Nullable<int> State_Id { get; set; }
        public string State_Name { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public string Country_Name { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string Telephone_Number { get; set; }
        public string Mobile_Number { get; set; }
        public string Email_Id { get; set; }
        public string Payment_Mode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Amount_In_Words { get; set; }
        public string DD_OR_Cheque_Number { get; set; }
        public Nullable<System.DateTime> DD_OR_Cheque_Date { get; set; }
        public string DD_OR_Cheque_BankName { get; set; }
        public string DD_OR_Cheque_Branch { get; set; }
        public string PANcard_Number { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> Receipt_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Type { get; set; }
        public string Transaction_Reference_PGI_Number { get; set; }
        public string Bank_Reference_Number { get; set; }
        public Nullable<decimal> Transaction_Amount { get; set; }
        public string Bank_Id { get; set; }
        public string Bank_Merchant_Id { get; set; }
        public string Transaction_Type { get; set; }
        public string Auth_Status { get; set; }
        public string Transaction_Date { get; set; }
        public string Auth_Status_Message { get; set; }
    }
}
