//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Challan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Payment_Order_No
    {
        public int Doc_Type_Id { get; set; }
        public string Doc_Type { get; set; }
        public string Financial_Year { get; set; }
        public int Institution_Id { get; set; }
        public int Starting_No { get; set; }
        public int Latest_No { get; set; }
        public string Module_Tag { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
    }
}
