//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Challan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Razorpay_Transaction
    {
        public long Id { get; set; }
        public long EChallan_Id { get; set; }
        public string Fee_Type { get; set; }
        public string OrderId { get; set; }
        public string PaymentAmt { get; set; }
        public string MID { get; set; }
        public string MKEY { get; set; }
        public string OrderIdParams { get; set; }
        public string RPayParams { get; set; }
        public string RPayOrderId { get; set; }
        public Nullable<System.DateTime> Initiated_Time { get; set; }
        public string CURRENCY { get; set; }
        public string GATEWAYNAME { get; set; }
        public string RESPMSG { get; set; }
        public string RPayPaymentId { get; set; }
        public string RpaySignature { get; set; }
        public string ValidateSignature { get; set; }
        public string TXN_STATUS { get; set; }
        public Nullable<System.DateTime> TXNDATE { get; set; }
        public string BANKNAME { get; set; }
        public string PAYMENTMODE { get; set; }
        public string RESPCODE { get; set; }
        public string TXNID { get; set; }
        public string TXNAMOUNT { get; set; }
        public string TXNCHARGE { get; set; }
        public string BANKTXNID { get; set; }
        public string CHECKSUMHASH { get; set; }
        public string ValidateCheckSum { get; set; }
        public string ResponseTimeStamp { get; set; }
        public string Version { get; set; }
        public string TXNTYPE { get; set; }
        public Nullable<bool> Status_Flag { get; set; }
    }
}
