//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Challan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User_Activites
    {
        public int Id { get; set; }
        public Nullable<int> EChallan_Id { get; set; }
        public string Type { get; set; }
        public Nullable<int> Done_By { get; set; }
        public string CurrentDate { get; set; }
        public string CurrentTime { get; set; }
    }
}
